// originally generated by 'threeport-sdk create' for API object
// scaffolding but will not be re-generated - intended for modification

package v0

import tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"

type DjangoDefinition struct {
	tpapi_v0.Common         `swaggerignore:"true" mapstructure:",squash"`
	tpapi_v0.Reconciliation `mapstructure:",squash"`
	tpapi_v0.Definition     `mapstructure:",squash"`
	DjangoInstances         []*DjangoInstance `validate:"optional,association"`
}

type DjangoInstance struct {
	tpapi_v0.Common         `swaggerignore:"true" mapstructure:",squash"`
	tpapi_v0.Reconciliation `mapstructure:",squash"`
	tpapi_v0.Instance       `mapstructure:",squash"`
	DjangoDefinitionID      *uint `validate:"required" gorm:"not null"`
}
