// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
	gorm "gorm.io/gorm"
)

// beforeCreate runs before the DjangoDefinition is created.
func (d *DjangoDefinition) beforeCreate(tx *gorm.DB) error {
	return validateIncomingEnvVars(d.Env, d.SecretEnvVars)
}

// beforeUpdate runs before the DjangoDefinition is updated.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - tpapi_lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
//
// Lower-level helpers, useful when tpapi_lib.IsFieldChanged doesn't fit:
//   - tpapi_lib.IncomingValues(tx): values being written
//   - tpapi_lib.IsFullReplace(tx): true on PUT (Save shape)
//   - tpapi_lib.IsPartialUpdate(tx): true on PATCH/DELETE (Updates shape)
//
// Import:
//
//	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (d *DjangoDefinition) beforeUpdate(tx *gorm.DB) error {
	// under PATCH the receiver is the loaded row, not what the caller sent
	if incoming, ok := tpapi_lib.IncomingValues(tx).(*DjangoDefinition); ok {
		return validateIncomingEnvVars(incoming.Env, incoming.SecretEnvVars)
	}
	return nil
}

// beforeDelete runs before the DjangoDefinition is deleted.
func (d *DjangoDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the DjangoDefinition is created.
func (d *DjangoDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the DjangoDefinition is updated.
func (d *DjangoDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the DjangoDefinition is deleted.
func (d *DjangoDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the DjangoInstance is created.
func (d *DjangoInstance) beforeCreate(tx *gorm.DB) error {
	return validateIncomingEnvVars(d.Env, d.SecretEnvVars)
}

// beforeUpdate runs before the DjangoInstance is updated.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - tpapi_lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
//
// Lower-level helpers, useful when tpapi_lib.IsFieldChanged doesn't fit:
//   - tpapi_lib.IncomingValues(tx): values being written
//   - tpapi_lib.IsFullReplace(tx): true on PUT (Save shape)
//   - tpapi_lib.IsPartialUpdate(tx): true on PATCH/DELETE (Updates shape)
//
// Import:
//
//	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (d *DjangoInstance) beforeUpdate(tx *gorm.DB) error {
	// under PATCH the receiver is the loaded row, not what the caller sent
	if incoming, ok := tpapi_lib.IncomingValues(tx).(*DjangoInstance); ok {
		return validateIncomingEnvVars(incoming.Env, incoming.SecretEnvVars)
	}
	return nil
}

// beforeDelete runs before the DjangoInstance is deleted.
func (d *DjangoInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the DjangoInstance is created.
func (d *DjangoInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the DjangoInstance is updated.
func (d *DjangoInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the DjangoInstance is deleted.
func (d *DjangoInstance) afterDelete(tx *gorm.DB) error {
	return nil
}
