// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	gorm "gorm.io/gorm"
)

// BeforeCreate is the GORM before-create hook for DjangoDefinition.
func (d *DjangoDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := d.beforeCreate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeCreate(tx, d)
}

// BeforeUpdate is the GORM before-update hook for DjangoDefinition.
func (d *DjangoDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := d.beforeUpdate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeUpdate(tx, d)
}

// BeforeDelete is the GORM before-delete hook for DjangoDefinition.
func (d *DjangoDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := d.beforeDelete(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeDelete(tx, d)
}

// AfterCreate is the GORM after-create hook for DjangoDefinition.
func (d *DjangoDefinition) AfterCreate(tx *gorm.DB) error {
	if err := d.afterCreate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterCreate(tx, d)
}

// AfterUpdate is the GORM after-update hook for DjangoDefinition.
func (d *DjangoDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := d.afterUpdate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterUpdate(tx, d)
}

// AfterDelete is the GORM after-delete hook for DjangoDefinition.
func (d *DjangoDefinition) AfterDelete(tx *gorm.DB) error {
	if err := d.afterDelete(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterDelete(tx, d)
}

// BeforeCreate is the GORM before-create hook for DjangoInstance.
func (d *DjangoInstance) BeforeCreate(tx *gorm.DB) error {
	if err := d.beforeCreate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeCreate(tx, d)
}

// BeforeUpdate is the GORM before-update hook for DjangoInstance.
func (d *DjangoInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := d.beforeUpdate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeUpdate(tx, d)
}

// BeforeDelete is the GORM before-delete hook for DjangoInstance.
func (d *DjangoInstance) BeforeDelete(tx *gorm.DB) error {
	if err := d.beforeDelete(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeDelete(tx, d)
}

// AfterCreate is the GORM after-create hook for DjangoInstance.
func (d *DjangoInstance) AfterCreate(tx *gorm.DB) error {
	if err := d.afterCreate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterCreate(tx, d)
}

// AfterUpdate is the GORM after-update hook for DjangoInstance.
func (d *DjangoInstance) AfterUpdate(tx *gorm.DB) error {
	if err := d.afterUpdate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterUpdate(tx, d)
}

// AfterDelete is the GORM after-delete hook for DjangoInstance.
func (d *DjangoInstance) AfterDelete(tx *gorm.DB) error {
	if err := d.afterDelete(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterDelete(tx, d)
}
