// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

// ApiNamespace is the module's api namespace; used as the
// prefix in this module's fully qualified type form.
const ApiNamespace = "threeport.io"

// Tabler allows custom table names for objects in the Threeport database.
type Tabler interface {
	TableName() string
}

// TableName sets the name of the table for the DjangoDefinition objects in the database.
func (DjangoDefinition) TableName() string {
	return "threeport_io_v0_django_definitions"
}

// TableName sets the name of the table for the DjangoInstance objects in the database.
func (DjangoInstance) TableName() string {
	return "threeport_io_v0_django_instances"
}
