// boilerplate generated by 'threeport-sdk gen' - do not edit

package main

import (
	"crypto/tls"
	"crypto/x509"
	util "django-threeport-module/cmd/rest-api/util"
	version "django-threeport-module/internal/version"
	apiserver_v0 "django-threeport-module/pkg/api-server/v0"
	database "django-threeport-module/pkg/api-server/v0/database"
	handlers_v0 "django-threeport-module/pkg/api-server/v0/handlers"
	routes_v0 "django-threeport-module/pkg/api-server/v0/routes"
	versions_v0 "django-threeport-module/pkg/api-server/v0/versions"
	"flag"
	"fmt"
	validator "github.com/go-playground/validator/v10"
	godotenv "github.com/joho/godotenv"
	echo "github.com/labstack/echo/v4"
	middleware "github.com/labstack/echo/v4/middleware"
	natsgo "github.com/nats-io/nats.go"
	tp_apiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	_ "github.com/threeport/threeport/pkg/api-server/v0/docs"
	tp_routes "github.com/threeport/threeport/pkg/api-server/v0/routes"
	client_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	tp_log "github.com/threeport/threeport/pkg/log/v0"
	zap "go.uber.org/zap"
	stdlog "log"
	"net/http"
	"os"
	"path/filepath"
)

// @title Django Threeport API
// @version v0.0.1-dev
// @description API server for the Threeport Django module.
// @contact.name Juan Jose Restrepo
// @contact.email juan.restrepo@intechideas.com
// @BasePath /threeport.io
func main() {
	// flags
	var threeportEnvFile string
	var moduleEnvFile string
	var autoMigrate bool
	var verbose bool
	var authEnabled bool
	var paginationMode string
	flag.StringVar(&threeportEnvFile, "threeport-env-file", "/etc/threeport/env", "File from which to load threeport environment")
	flag.StringVar(&moduleEnvFile, "module-env-file", "/etc/threeport/mod/env", "File from which to load module environment")
	flag.BoolVar(&autoMigrate, "auto-migrate", false, "If true API server will auto migrate DB schema")
	flag.BoolVar(&verbose, "verbose", false, "Write logs with v(1).InfoLevel and above")
	flag.BoolVar(&authEnabled, "auth-enabled", true, "Enable client certificate authentication")
	flag.StringVar(&paginationMode, "pagination-mode", string(tp_apiserver_lib.PaginationModeAsOfSystemTime), "Pagination backend: as-of-system-time | materialized-view")
	flag.Parse()
	if !tp_apiserver_lib.ValidPaginationMode(paginationMode) {
		stdlog.Fatalf("invalid pagination-mode %q, want as-of-system-time or materialized-view", paginationMode)
	}

	// set up echo
	e := echo.New()
	e.HideBanner = true

	// bind query params to struct fields by lowercased field name,
	// so api types don't need `query:"..."` struct tags
	e.Binder = tp_apiserver_lib.NewQueryBinder()

	// omit absent fields from responses instead of spelling them
	// out as null, so api types don't need `json:",omitempty"`
	// struct tags
	e.JSONSerializer = tp_apiserver_lib.NewJSONSerializer()

	var validate *validator.Validate
	validate = validator.New()
	validate.RegisterValidation("optional", tp_apiserver_lib.IsOptional)
	validate.RegisterValidation("association", tp_apiserver_lib.IsAssociation)
	validate.RegisterValidation("ISO8601date", tp_apiserver_lib.IsISO8601Date)
	e.Validator = &tp_apiserver_lib.CustomValidator{Validator: validate}

	// middleware
	e.Use(func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			cc := &tp_apiserver_lib.CustomContext{Context: c}
			return next(cc)
		}
	})

	// capture the request's mTLS peer identity so GORM hooks can read it via
	// apiserver_lib.Caller(tx.Statement.Context)
	e.Use(tp_apiserver_lib.CaptureCaller(authEnabled))

	logger, err := tp_log.NewLogger(verbose)
	if err != nil {
		panic(err)
	}
	e.Logger = tp_log.NewEchoLogger(&logger)
	e.Use(middleware.RequestLoggerWithConfig(middleware.RequestLoggerConfig{
		LogError:    true,
		LogHost:     true,
		LogLatency:  true,
		LogMethod:   true,
		LogRemoteIP: true,
		LogStatus:   true,
		LogURI:      true,
		LogValuesFunc: func(c echo.Context, v middleware.RequestLoggerValues) error {
			logger.Info(
				"request",
				zap.String("method", v.Method),
				zap.String("uri", v.URI),
				zap.Int("status", v.Status),
				zap.String("remoteIP", v.RemoteIP),
				zap.String("host", v.Host),
				zap.Duration("latency", v.Latency),
				zap.Error(v.Error),
			)
			return nil
		},
	}))
	e.Use(middleware.Recover())

	e.HTTPErrorHandler = func(err error, c echo.Context) {
		// call the default handler to return the HTTP response
		e.DefaultHTTPErrorHandler(err, c)
	}

	// threeport and module environment variables
	if err := godotenv.Load(threeportEnvFile); err != nil {
		e.Logger.Fatalf("failed to load threeport environment variables: %v", err)
	}
	if err := godotenv.Load(moduleEnvFile); err != nil {
		e.Logger.Fatalf("failed to load module environment variables: %v", err)
	}

	// database connection
	db, err := database.Init(autoMigrate, &logger)
	if err != nil {
		e.Logger.Fatalf("failed to initialize database: %v", err)
	}

	// get a client for the core threeport API to use for registering the module
	tpApiEndpoint := os.Getenv("THREEPORT_API_ENDPOINT")
	if tpApiEndpoint == "" {
		e.Logger.Fatalf("THREEPORT_API_ENDPOINT is not set in environment")
	}
	tpAuthEnabled := os.Getenv("THREEPORT_AUTH_ENABLED")
	if tpAuthEnabled == "" {
		e.Logger.Fatalf("THREEPORT_AUTH_ENABLED is not set in environment")
	}
	tpClient, err := client_lib.GetHTTPClient(tpAuthEnabled == "true", "", "", "", "")
	if err != nil {
		e.Logger.Fatalf("failed to get core threeport API client: %v", err)
	}

	// register module information in the database as needed
	moduleApiEndpoint := os.Getenv("MODULE_API_ENDPOINT")
	if moduleApiEndpoint == "" {
		e.Logger.Fatalf("MODULE_API_ENDPOINT is not set in environment")
	}
	moduleNamespace := os.Getenv("MODULE_NAMESPACE")
	if moduleNamespace == "" {
		e.Logger.Fatalf("MODULE_NAMESPACE is not set in environment")
	}
	if err := apiserver_v0.RegisterModule(
		tpClient,
		tpApiEndpoint,
		moduleApiEndpoint,
		moduleNamespace,
	); err != nil {
		e.Logger.Fatalf("failed to register module: %v", err)
	}

	// nats connection
	natsConn := fmt.Sprintf(
		"nats://%s:%s@%s:%s",
		os.Getenv("NATS_USER"),
		os.Getenv("NATS_PASSWORD"),
		os.Getenv("NATS_HOST"),
		os.Getenv("NATS_PORT"),
	)
	nc, err := natsgo.Connect(natsConn)
	if err != nil {
		e.Logger.Fatalf("failed to establish nats connection: %v", err)
	}
	defer nc.Close()

	// jetstream context
	js, err := util.InitJetStream(nc)
	if err != nil {
		e.Logger.Fatalf("failed to initialize nats jet stream: %v", err)
	}

	// handlers
	// v0
	h_v0 := handlers_v0.New(db, nc, *js, &logger)
	h_v0.Handler.PaginationMode = tp_apiserver_lib.PaginationMode(paginationMode)

	// routes
	tp_routes.SwaggerRoutes(e)
	util.VersionRoute(e)

	// v0
	routes_v0.AddRoutes(e, &h_v0)
	routes_v0.AddCustomRoutes(e, &h_v0)

	// add version info for queries to /<object>/versions
	tp_apiserver_lib.Versions[0] = "v0"
	versions_v0.AddVersions()

	if authEnabled {
		configDir := "/etc/threeport"

		// load server certificate and private key
		cert, err := tls.LoadX509KeyPair(filepath.Join(configDir, "cert/tls.crt"), filepath.Join(configDir, "cert/tls.key"))
		if err != nil {
			e.Logger.Fatal(err)
		}

		// load server root certificate authority
		caCert, err := os.ReadFile(filepath.Join(configDir, "ca/tls.crt"))
		if err != nil {
			e.Logger.Fatal(err)
		}

		// create certificate pool and add server root certificate authority
		caCertPool := x509.NewCertPool()
		if ok := caCertPool.AppendCertsFromPEM(caCert); !ok {
			e.Logger.Fatal("failed to parse certificate authority")
		}

		// configure https server
		server := http.Server{
			Addr:    ":1323",
			Handler: e,
			TLSConfig: &tls.Config{
				Certificates: []tls.Certificate{cert},
				ClientAuth:   tls.RequireAndVerifyClientCert,
				ClientCAs:    caCertPool,
				RootCAs:      caCertPool,
			},
		}

		e.Logger.Infof("Threeport module REST API for API namespace threeport.io: %s", version.GetVersion())
		configureHealthCheckEndpoint()
		if serveErr := server.ListenAndServeTLS("", ""); serveErr != http.ErrServerClosed {
			e.Logger.Fatal(serveErr)
		}
	} else {
		// configure http server
		server := http.Server{
			Addr:    ":1323",
			Handler: e,
		}

		e.Logger.Infof("Threeport module REST API for API namespace threeport.io: %s", version.GetVersion())
		configureHealthCheckEndpoint()
		if serveErr := server.ListenAndServe(); serveErr != http.ErrServerClosed {
			e.Logger.Fatal(serveErr)
		}
	}
}

// configureHealthCheckEndpoint sets up a health check endpoint for the API server
func configureHealthCheckEndpoint() {
	// set up health check endpoint
	http.HandleFunc("/readyz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("OK"))
	})

	go http.ListenAndServe(":8081", nil)
}
