// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	routes "django-threeport-module/pkg/api-server/v0/routes"
	api_v0 "django-threeport-module/pkg/api/v0"
	"errors"
	"fmt"
	tp_api "github.com/threeport/threeport/pkg/api/v0"
	tp_client_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	tp_client "github.com/threeport/threeport/pkg/client/v0"
	tp_util "github.com/threeport/threeport/pkg/util/v0"
	"log"
	"net/http"
)

const (
	moduleName = "threeport.io/django-module-api"
)

// resolveModuleApi looks up the module API by name. It returns the record
// when one is registered under that name, and otherwise reports that a fresh
// record must be created.
func resolveModuleApi(tpApiClient *http.Client, tpApiAddr string) (*tp_api.ModuleApi, bool, error) {
	existingModApi, err := tp_client.GetModuleApiByName(tpApiClient, tpApiAddr, moduleName)
	if err == nil {
		log.Printf("register-module: found existing module api %q", moduleName)
		return existingModApi, false, nil
	}
	if !errors.Is(err, tp_client_lib.ErrObjectNotFound) {
		return nil, false, fmt.Errorf("failed to check for existing module API: %w", err)
	}

	return nil, true, nil
}

// upsertModuleController creates the module controller. When the create
// hits a name conflict, it looks up the existing row by name alone and, if
// that row points at a different module_api_id, updates it to the current
// one so the module claims the controller instead of colliding with it.
func upsertModuleController(tpApiClient *http.Client, tpApiAddr string, controller *tp_api.ModuleController, moduleApiID *uint) (*tp_api.ModuleController, error) {
	created, createErr := tp_client.CreateModuleController(tpApiClient, tpApiAddr, controller)
	if createErr == nil {
		return created, nil
	}
	if !errors.Is(createErr, tp_client_lib.ErrConflict) {
		return nil, createErr
	}

	log.Printf("register-module: controller %q create hit conflict; checking which module api owns it", *controller.Name)
	existing, lookupErr := tp_client.GetModuleControllerByName(tpApiClient, tpApiAddr, *controller.Name)
	if lookupErr != nil {
		return nil, fmt.Errorf("failed to look up conflicting controller %q by name: %w", *controller.Name, lookupErr)
	}
	if existing.ModuleApiID != nil && *existing.ModuleApiID == *moduleApiID {
		log.Printf("register-module: controller %q already bound to current module api %d", *controller.Name, *moduleApiID)
		return existing, nil
	}
	priorModuleApi := "none"
	if existing.ModuleApiID != nil {
		priorModuleApi = fmt.Sprintf("%d", *existing.ModuleApiID)
	}
	log.Printf("register-module: rebinding controller %q from module api %s to %d", *controller.Name, priorModuleApi, *moduleApiID)
	existing.ModuleApiID = moduleApiID
	existing.DeploymentName = controller.DeploymentName
	updated, upErr := tp_client.UpdateModuleController(tpApiClient, tpApiAddr, existing)
	if upErr != nil {
		return nil, fmt.Errorf("failed to rebind controller %q to current module api: %w", *controller.Name, upErr)
	}
	return updated, nil
}

// RegisterModule calls the Threeport API to register the module with core Threeport.
// This ensures that module object requests are proxied to the module API by the
// Threeport API server.
func RegisterModule(
	tpApiClient *http.Client,
	tpApiAddr string,
	moduleApiEndpoint string,
	moduleNamespace string,
) error {
	// look up the module API so a re-registration reuses the existing
	// record along with the controller and object rows that reference it
	existingModApi, createFresh, err := resolveModuleApi(tpApiClient, tpApiAddr)
	if err != nil {
		return err
	}
	if createFresh {
		// register the module in the Threeport API with the ModuleApi object
		log.Printf("register-module: no existing module api; creating %q", moduleName)
		moduleApi := tp_api.ModuleApi{
			ApiNamespace: tp_util.Ptr(api_v0.ApiNamespace),
			Endpoint:     tp_util.Ptr(moduleApiEndpoint),
			Name:         tp_util.Ptr(moduleName),
		}
		createdModApi, createErr := tp_client.CreateModuleApi(tpApiClient, tpApiAddr, &moduleApi)
		if createErr != nil {
			return fmt.Errorf("failed to create module API object in Threeport API: %w", createErr)
		}
		existingModApi = createdModApi
	}
	///////////////////////////////////////////////////////////////////////////////
	// registering controllers, objects and routes for Django object group
	///////////////////////////////////////////////////////////////////////////////
	// registering controller django-controller
	djangoControllerSlice, djangoControllerErr := tp_client.GetModuleControllersByQueryString(
		tpApiClient,
		tpApiAddr,
		fmt.Sprintf("name=%s&moduleapiid=%d", "django-controller", *existingModApi.ID),
	)
	if djangoControllerErr != nil {
		return fmt.Errorf("failed to check for existing controller django-controller: %w", djangoControllerErr)
	}
	var djangoController tp_api.ModuleController
	if len(*djangoControllerSlice) == 0 {
		// controller doesn't exist - create it
		controller := tp_api.ModuleController{
			DeploymentName: tp_util.Ptr(moduleNamespace + "/threeport-django-controller"),
			ModuleApiID:    existingModApi.ID,
			Name:           tp_util.Ptr("django-controller"),
		}
		// the lookup above is scoped to this module api, so a row
		// under a different one is invisible here and only shows up
		// as a name conflict on the create
		createdController, err := upsertModuleController(tpApiClient, tpApiAddr, &controller, existingModApi.ID)
		if err != nil {
			return fmt.Errorf("failed to register module controller django-controller in Threeport API: %w", err)
		}
		djangoController = *createdController

	} else if len(*djangoControllerSlice) == 1 {
		djangoController = (*djangoControllerSlice)[0]
	} else {
		return fmt.Errorf("expected 0 or 1 module controllers for django-controller, got %d", len(*djangoControllerSlice))
	}

	// registering object DjangoDefinition
	var djangoDefinition tp_api.ModuleObject
	djangoDefinitionSlice, djangoDefinitionErr := tp_client.GetModuleObjectsByQueryString(
		tpApiClient,
		tpApiAddr,
		fmt.Sprintf("name=DjangoDefinition&moduleapiid=%d", *existingModApi.ID),
	)
	if djangoDefinitionErr != nil {
		return fmt.Errorf("failed to check for existing object DjangoDefinition: %w", djangoDefinitionErr)
	}
	if len(*djangoDefinitionSlice) == 0 {
		object := tp_api.ModuleObject{
			Description:        tp_util.Ptr(""),
			ModuleApiID:        existingModApi.ID,
			ModuleControllerID: djangoController.ID,
			Name:               tp_util.Ptr("DjangoDefinition"),
			Version:            tp_util.Ptr("v0"),
		}
		objectResult, err := tp_client.CreateModuleObject(tpApiClient, tpApiAddr, &object)
		if err != nil {
			return fmt.Errorf("failed to create module object DjangoDefinition in Threeport API: %w", err)
		}
		djangoDefinition = *objectResult
	} else if len(*djangoDefinitionSlice) == 1 {
		djangoDefinition = (*djangoDefinitionSlice)[0]
	} else {
		return fmt.Errorf("expected 0 or 1 module objects for DjangoDefinition, got %d", len(*djangoDefinitionSlice))
	}

	// registering routes for DjangoDefinition
	djangoDefinitionRoute := tp_api.ModuleApiRoute{
		ModuleApiID:   existingModApi.ID,
		ModuleObjects: []*tp_api.ModuleObject{&djangoDefinition},
		Path:          tp_util.Ptr(api_v0.PathDjangoDefinitionVersions),
	}
	_, djangoDefinitionRouteErr := tp_client.CreateModuleApiRouteWithModuleObjectReferences(
		tpApiClient,
		tpApiAddr,
		&djangoDefinitionRoute,
	)
	if djangoDefinitionRouteErr != nil && !errors.Is(djangoDefinitionRouteErr, tp_client_lib.ErrConflict) {
		return fmt.Errorf("failed to create module route for DjangoDefinition version in Threeport API: %w", djangoDefinitionRouteErr)
	}
	djangoDefinitionRoute = tp_api.ModuleApiRoute{
		ModuleApiID:   existingModApi.ID,
		ModuleObjects: []*tp_api.ModuleObject{&djangoDefinition},
		Path:          tp_util.Ptr(api_v0.PathDjangoDefinitions),
	}
	_, djangoDefinitionRouteErr = tp_client.CreateModuleApiRouteWithModuleObjectReferences(
		tpApiClient,
		tpApiAddr,
		&djangoDefinitionRoute,
	)
	if djangoDefinitionRouteErr != nil && !errors.Is(djangoDefinitionRouteErr, tp_client_lib.ErrConflict) {
		return fmt.Errorf("failed to create module route for DjangoDefinition in Threeport API: %w", djangoDefinitionRouteErr)
	}

	// registering object DjangoInstance
	var djangoInstance tp_api.ModuleObject
	djangoInstanceSlice, djangoInstanceErr := tp_client.GetModuleObjectsByQueryString(
		tpApiClient,
		tpApiAddr,
		fmt.Sprintf("name=DjangoInstance&moduleapiid=%d", *existingModApi.ID),
	)
	if djangoInstanceErr != nil {
		return fmt.Errorf("failed to check for existing object DjangoInstance: %w", djangoInstanceErr)
	}
	if len(*djangoInstanceSlice) == 0 {
		object := tp_api.ModuleObject{
			Description:        tp_util.Ptr(""),
			ModuleApiID:        existingModApi.ID,
			ModuleControllerID: djangoController.ID,
			Name:               tp_util.Ptr("DjangoInstance"),
			Version:            tp_util.Ptr("v0"),
		}
		objectResult, err := tp_client.CreateModuleObject(tpApiClient, tpApiAddr, &object)
		if err != nil {
			return fmt.Errorf("failed to create module object DjangoInstance in Threeport API: %w", err)
		}
		djangoInstance = *objectResult
	} else if len(*djangoInstanceSlice) == 1 {
		djangoInstance = (*djangoInstanceSlice)[0]
	} else {
		return fmt.Errorf("expected 0 or 1 module objects for DjangoInstance, got %d", len(*djangoInstanceSlice))
	}

	// registering routes for DjangoInstance
	djangoInstanceRoute := tp_api.ModuleApiRoute{
		ModuleApiID:   existingModApi.ID,
		ModuleObjects: []*tp_api.ModuleObject{&djangoInstance},
		Path:          tp_util.Ptr(api_v0.PathDjangoInstanceVersions),
	}
	_, djangoInstanceRouteErr := tp_client.CreateModuleApiRouteWithModuleObjectReferences(
		tpApiClient,
		tpApiAddr,
		&djangoInstanceRoute,
	)
	if djangoInstanceRouteErr != nil && !errors.Is(djangoInstanceRouteErr, tp_client_lib.ErrConflict) {
		return fmt.Errorf("failed to create module route for DjangoInstance version in Threeport API: %w", djangoInstanceRouteErr)
	}
	djangoInstanceRoute = tp_api.ModuleApiRoute{
		ModuleApiID:   existingModApi.ID,
		ModuleObjects: []*tp_api.ModuleObject{&djangoInstance},
		Path:          tp_util.Ptr(api_v0.PathDjangoInstances),
	}
	_, djangoInstanceRouteErr = tp_client.CreateModuleApiRouteWithModuleObjectReferences(
		tpApiClient,
		tpApiAddr,
		&djangoInstanceRoute,
	)
	if djangoInstanceRouteErr != nil && !errors.Is(djangoInstanceRouteErr, tp_client_lib.ErrConflict) {
		return fmt.Errorf("failed to create module route for DjangoInstance in Threeport API: %w", djangoInstanceRouteErr)
	}

	// registering custom routes
	for _, customRoute := range *routes.CustomRoutes(nil) {
		// query the module objects for the custom route by name and version
		moduleObjects := []*tp_api.ModuleObject{}
		for _, apiObject := range *customRoute.ApiObjects {
			modObj, err := tp_client.GetModuleObjectsByQueryString(
				tpApiClient,
				tpApiAddr,
				fmt.Sprintf("name=%s&version=%s", apiObject.Name, apiObject.Version),
			)
			if err != nil {
				return fmt.Errorf("failed to retrieve module object %s: %w", apiObject.Name, err)
			}
			moduleObjects = append(moduleObjects, &(*modObj)[0])
		}
		route := tp_api.ModuleApiRoute{
			ModuleApiID:   existingModApi.ID,
			ModuleObjects: moduleObjects,
			Path:          tp_util.Ptr(customRoute.Path),
		}
		_, customRouteErr := tp_client.CreateModuleApiRouteWithModuleObjectReferences(
			tpApiClient,
			tpApiAddr,
			&route,
		)
		if customRouteErr != nil && !errors.Is(customRouteErr, tp_client_lib.ErrConflict) {
			return fmt.Errorf("failed to create module route for custom route %s: %w", customRoute.Path, customRouteErr)
		}
	}

	return nil
}
