// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	config_v0 "django-threeport-module/pkg/config/v0"
	"fmt"
	"os"
	"text/tabwriter"
)

// outputGetv0DjangosCmd produces the tabular output for the
// 'get djangos' command.
func outputGetv0DjangosCmd(
	djangos *[]config_v0.DjangoConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the DjangoValues object in pkg/config/v0/django.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, django := range *djangos {
		fmt.Fprintln(
			writer,
			*django.Django.Name, "\t",
			*django.Django.Age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0DjangoDefinitionsCmd produces the tabular output for the
// `get django-definitions` command.
func outputGetv0DjangoDefinitionsCmd(
	djangoDefinitions *[]config_v0.DjangoDefinitionConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the DjangoDefinitionValues object in pkg/config/v0/django_definition.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, djangoDefinition := range *djangoDefinitions {
		fmt.Fprintln(
			writer,
			*djangoDefinition.DjangoDefinition.Name, "\t",
			*djangoDefinition.DjangoDefinition.Age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0DjangoInstancesCmd produces the tabular output for the
// `get django-instances` command.
func outputGetv0DjangoInstancesCmd(
	djangoInstances *[]config_v0.DjangoInstanceConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the DjangoInstanceValues object in pkg/config/v0/django_instance.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, djangoInstance := range *djangoInstances {
		fmt.Fprintln(
			writer,
			*djangoInstance.DjangoInstance.Name, "\t",
			*djangoInstance.DjangoInstance.Age,
		)
	}
	writer.Flush()

	return nil
}
