// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	version "django-threeport-module/internal/version"
	installer "django-threeport-module/pkg/installer/v0"
	"fmt"
	cobra "github.com/spf13/cobra"
	tptctl_cmd "github.com/threeport/threeport/cmd/tptctl/cmd"
	cli "github.com/threeport/threeport/pkg/cli/v0"
	client "github.com/threeport/threeport/pkg/client/v0"
	kube "github.com/threeport/threeport/pkg/kube/v0"
	"os"
)

var (
	debug                 bool
	controlPlaneImageRepo string
	controlPlaneImageTag  string
	imagePullSecretFile   string
)

// installCmd represents the install command
var installCmd = &cobra.Command{
	Example: "  tptctl django install",
	Long:    "Install the Django module to an existing Threeport control plane",
	PreRun:  tptctl_cmd.CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, requestedControlPlane := tptctl_cmd.GetClientContext(cmd)

		// get Kubernetes runtime instance for control plane
		queryString := "ThreeportControlPlaneHost=true"
		kubernetesRuntimeInstances, err := client.GetKubernetesRuntimeInstancesByQueryString(
			apiClient,
			apiEndpoint,
			queryString,
		)
		if err != nil {
			cli.Error("failed to get kubernetes runtime instances", err)
			os.Exit(1)
		}
		if len(*kubernetesRuntimeInstances) != 1 {
			cli.Error(fmt.Sprintf("found %d k8s runtime instances", len(*kubernetesRuntimeInstances)), err)
			os.Exit(1)
		}
		kubeRuntimes := *kubernetesRuntimeInstances

		// get threeport config
		threeportConfig, _, err := cli.GetThreeportConfig(requestedControlPlane)
		if err != nil {
			cli.Error("failed to get threeport config", err)
			os.Exit(1)
		}

		// get encryption key
		encryptionKey, err := threeportConfig.GetThreeportEncryptionKey(requestedControlPlane)
		if err != nil {
			cli.Error("failed to get Threeport API encryption key", err)
			os.Exit(1)
		}

		// determine if auth is enabled on control plane
		authEnabled, err := threeportConfig.GetThreeportAuthEnabled(requestedControlPlane)
		if err != nil {
			cli.Error("failed to determine if auth is enabled", err)
			os.Exit(1)
		}

		// get Kubernetes client
		dynamicInterface, restMapper, err := kube.GetClient(
			&kubeRuntimes[0],
			false,
			apiClient,
			apiEndpoint,
			encryptionKey,
		)
		if err != nil {
			cli.Error("failed to get Kube client", err)
			os.Exit(1)
		}

		// create installer
		inst := installer.NewInstaller(dynamicInterface, restMapper)
		inst.AuthEnabled = authEnabled
		inst.ControlPlaneImageRepo = controlPlaneImageRepo
		inst.ControlPlaneImageTag = controlPlaneImageTag
		inst.Debug = debug
		inst.ApiClient = apiClient
		inst.ApiEndpoint = apiEndpoint
		inst.ImagePullSecretFile = imagePullSecretFile

		// install extension module
		if err := inst.InstallDjangoModule(); err != nil {
			cli.Error("failed to install Django module", err)
			os.Exit(1)
		}

		cli.Complete("Django module installed")
	},
	Short:        "Install the Django module to an existing Threeport control plane",
	SilenceUsage: true,
	Use:          "install",
}

func init() {
	rootCmd.AddCommand(installCmd)

	installCmd.Flags().BoolVar(
		&debug,
		"debug",
		false,
		"If true, pod imagePullPolicy is set to Always so each rollout re-pulls the tag.",
	)
	installCmd.Flags().StringVarP(
		&controlPlaneImageRepo,
		"control-plane-image-namespace", "r", installer.ReleaseImageNamespace, "Image namespace to pull threeport control plane images from.",
	)
	installCmd.Flags().StringVarP(
		&controlPlaneImageTag,
		"control-plane-image-tag", "t", version.GetVersion(), "Image tag for threeport control plane images.",
	)
	installCmd.Flags().StringVar(
		&imagePullSecretFile,
		"image-pull-secret-file", "", "Path to a docker config JSON file. When set, a dockerconfigjson Secret is created and referenced from each component's imagePullSecrets so the kubelet can pull from a private registry.",
	)
}
