// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import cobra "github.com/spf13/cobra"

// ReplaceCmd represents the replace command
var ReplaceCmd = &cobra.Command{
	Long:  "Replace a Threeport Django object.\n\n\tThe replace command does nothing by itself.  Use one of the available subcommands\n\tto replace different objects from the system.",
	Short: "Replace a Threeport Django object",
	Use:   "replace",
}

func init() {
	rootCmd.AddCommand(ReplaceCmd)
}
