// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	version "django-threeport-module/internal/version"
	"fmt"
	cobra "github.com/spf13/cobra"
)

// versionCmd represents the version command for the Django plugin
var versionCmd = &cobra.Command{
	Long: "Print the version of django",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println(version.GetVersion())
	},
	Short: "Print the version of django",
	Use:   "version",
}

func init() {
	rootCmd.AddCommand(versionCmd)
}
