// boilerplate generated by 'threeport-sdk gen' - do not edit

package django

// The name and description of the NATS bucket used for django object locks
const (
	LockBucketName  = "djangoLock"
	LockBucketDescr = "contains locks on django objects"
)
