// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package django

import (
	v0 "django-threeport-module/pkg/api/v0"
	logr "github.com/go-logr/logr"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0DjangoInstanceCreated performs reconciliation when a v0 DjangoInstance
// has been created.
func v0DjangoInstanceCreated(
	r *controller.Reconciler,
	djangoInstance *v0.DjangoInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0DjangoInstanceUpdated performs reconciliation when a v0 DjangoInstance
// has been updated.
func v0DjangoInstanceUpdated(
	r *controller.Reconciler,
	djangoInstance *v0.DjangoInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0DjangoInstanceDeleted performs reconciliation when a v0 DjangoInstance
// has been deleted.
func v0DjangoInstanceDeleted(
	r *controller.Reconciler,
	djangoInstance *v0.DjangoInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
