// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package django

import (
	v0 "django-threeport-module/pkg/api/v0"
	logr "github.com/go-logr/logr"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0DjangoDefinitionCreated performs reconciliation when a v0 DjangoDefinition
// has been created.
func v0DjangoDefinitionCreated(
	r *controller.Reconciler,
	djangoDefinition *v0.DjangoDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0DjangoDefinitionUpdated performs reconciliation when a v0 DjangoDefinition
// has been updated.
func v0DjangoDefinitionUpdated(
	r *controller.Reconciler,
	djangoDefinition *v0.DjangoDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0DjangoDefinitionDeleted performs reconciliation when a v0 DjangoDefinition
// has been deleted.
func v0DjangoDefinitionDeleted(
	r *controller.Reconciler,
	djangoDefinition *v0.DjangoDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
