// boilerplate generated by 'threeport-sdk gen' - do not edit

package util

import (
	notif "django-threeport-module/internal/django/notif"
	"fmt"
	nats "github.com/nats-io/nats.go"
)

// Initialize the NATS Jet stream context with controller streams
func InitJetStream(nc *nats.Conn) (*nats.JetStreamContext, error) {
	js, err := nc.JetStream(nats.PublishAsyncMaxPending(256))
	if err != nil {
		return nil, fmt.Errorf("failed to create jetstream context: %w", err)
	}

	// add controller streams
	_, err = js.AddStream(&nats.StreamConfig{
		Name:     notif.DjangoStreamName,
		Subjects: notif.GetDjangoSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not add stream %s: %w", notif.DjangoStreamName, err)
	}

	return &js, nil
}
