// boilerplate generated by 'threeport-sdk gen' - do not edit

package routes

import (
	handlers "django-threeport-module/pkg/api-server/v0/handlers"
	v0 "django-threeport-module/pkg/api/v0"
	echo "github.com/labstack/echo/v4"
)

// DjangoDefinitionRoutes sets up all routes for the DjangoDefinition handlers.
func DjangoDefinitionRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathDjangoDefinitionVersions, h.GetDjangoDefinitionVersions)

	e.POST(v0.PathDjangoDefinitions, h.AddDjangoDefinition)
	e.GET(v0.PathDjangoDefinitions, h.GetDjangoDefinitions)
	e.GET(v0.PathDjangoDefinitions+"/:id", h.GetDjangoDefinition)
	e.PATCH(v0.PathDjangoDefinitions+"/:id", h.UpdateDjangoDefinition)
	e.PUT(v0.PathDjangoDefinitions+"/:id", h.ReplaceDjangoDefinition)
	e.DELETE(v0.PathDjangoDefinitions+"/:id", h.DeleteDjangoDefinition)
}

// DjangoInstanceRoutes sets up all routes for the DjangoInstance handlers.
func DjangoInstanceRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathDjangoInstanceVersions, h.GetDjangoInstanceVersions)

	e.POST(v0.PathDjangoInstances, h.AddDjangoInstance)
	e.GET(v0.PathDjangoInstances, h.GetDjangoInstances)
	e.GET(v0.PathDjangoInstances+"/:id", h.GetDjangoInstance)
	e.PATCH(v0.PathDjangoInstances+"/:id", h.UpdateDjangoInstance)
	e.PUT(v0.PathDjangoInstances+"/:id", h.ReplaceDjangoInstance)
	e.DELETE(v0.PathDjangoInstances+"/:id", h.DeleteDjangoInstance)
}
