// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package routes

import (
	handlers "django-threeport-module/pkg/api-server/v0/handlers"
	echo "github.com/labstack/echo/v4"
	tp_routes "github.com/threeport/threeport/pkg/api-server/v0/routes"
)

// CustomRoutes returns a list of all custom routes for the API.
// Any custom routes that are added to the API must be added here.
// This will ensure the routes are added to the API server and are
// registered in the ModuleApiRoutes table in the database.
func CustomRoutes(h *handlers.Handler) *[]tp_routes.CustomRoute {
	// if the caller doesn't provide a handler, use an empty handler as a dummy
	if h == nil {
		h = &handlers.Handler{}
	}

	// Add custom routes here.  Example:
	//
	//	return &[]tp_routes.CustomRoute{
	//	    {
	//	        Path: api_v0.PathCustomForSomeObject,
	//	        Method: "POST",
	//	        Handler: tp_util.Ptr(h.CustomerHandlerForSomeObject),
	//	        ApiObjects: &[]ApiObject{
	//	            {
	//	                Name: "SomeObject",
	//	                Version: "v0",
	//	            },
	//	        },
	//	    },
	//	}
	return &[]tp_routes.CustomRoute{}
}

// AddCustomRoutes adds non-SDK-generated routes to API server for custom use cases.
func AddCustomRoutes(e *echo.Echo, h *handlers.Handler) {
	for _, route := range *CustomRoutes(h) {
		if route.Handler != nil {
			e.Add(route.Method, route.Path, *route.Handler)
		}
		if route.IdParamHandler != nil {
			e.Add(route.Method, route.Path+"/:id", *route.IdParamHandler)
		}
	}
}
