// boilerplate generated by 'threeport-sdk gen' - do not edit

package routes

import (
	handlers "django-threeport-module/pkg/api-server/v0/handlers"
	echo "github.com/labstack/echo/v4"
)

// AddRoutes adds routes for all objects of a particular API version.
func AddRoutes(e *echo.Echo, h *handlers.Handler) {
	DjangoDefinitionRoutes(e, h)
	DjangoInstanceRoutes(e, h)
}
