// boilerplate generated by 'threeport-sdk gen' - do not edit

package notif

const (
	DjangoStreamName = "threeport-io_djangoStream"

	DjangoDefinitionSubject       = "threeport-io_djangoDefinition.*"
	DjangoDefinitionCreateSubject = "threeport-io_djangoDefinition.create"
	DjangoDefinitionUpdateSubject = "threeport-io_djangoDefinition.update"
	DjangoDefinitionDeleteSubject = "threeport-io_djangoDefinition.delete"

	DjangoInstanceSubject       = "threeport-io_djangoInstance.*"
	DjangoInstanceCreateSubject = "threeport-io_djangoInstance.create"
	DjangoInstanceUpdateSubject = "threeport-io_djangoInstance.update"
	DjangoInstanceDeleteSubject = "threeport-io_djangoInstance.delete"
)

// GetDjangoDefinitionSubjects returns the NATS subjects
// for django definitions.
func GetDjangoDefinitionSubjects() []string {
	return []string{
		DjangoDefinitionCreateSubject,
		DjangoDefinitionUpdateSubject,
		DjangoDefinitionDeleteSubject,
	}
}

// GetDjangoInstanceSubjects returns the NATS subjects
// for django instances.
func GetDjangoInstanceSubjects() []string {
	return []string{
		DjangoInstanceCreateSubject,
		DjangoInstanceUpdateSubject,
		DjangoInstanceDeleteSubject,
	}
}

// GetDjangoSubjects returns the NATS subjects
// for all django objects.
func GetDjangoSubjects() []string {
	var djangoSubjects []string

	djangoSubjects = append(djangoSubjects, GetDjangoDefinitionSubjects()...)
	djangoSubjects = append(djangoSubjects, GetDjangoInstanceSubjects()...)

	return djangoSubjects
}
