// boilerplate generated by 'threeport-sdk gen' - do not edit

package versions

import (
	apiserver_v0 "django-threeport-module/pkg/api-server/v0"
	api_v0 "django-threeport-module/pkg/api/v0"
	tpapiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
	"reflect"
)

// AddDjangoDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddDjangoDefinitionVersions() {
	apiserver_v0.DjangoDefinitionTaggedFields[string(tpapi_lib.ValidateTag)] = &tpapiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(tpapi_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	tpapiserver_lib.ParseStruct(
		string(tpapi_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.DjangoDefinition)),
		"",
		tpapiserver_lib.Translate,
		apiserver_v0.DjangoDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := tpapiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeDjangoDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	tpapiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.DjangoDefinitionTaggedFields[string(tpapi_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	tpapiserver_lib.AddObjectVersion(versionObj)
}

// AddDjangoInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddDjangoInstanceVersions() {
	apiserver_v0.DjangoInstanceTaggedFields[string(tpapi_lib.ValidateTag)] = &tpapiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(tpapi_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	tpapiserver_lib.ParseStruct(
		string(tpapi_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.DjangoInstance)),
		"",
		tpapiserver_lib.Translate,
		apiserver_v0.DjangoInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := tpapiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeDjangoInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	tpapiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.DjangoInstanceTaggedFields[string(tpapi_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	tpapiserver_lib.AddObjectVersion(versionObj)
}
