// boilerplate generated by 'threeport-sdk gen' - do not edit

package main

import (
	version "django-threeport-module/internal/version"
	installer "django-threeport-module/pkg/installer/v0"
	"fmt"
	mg "github.com/magefile/mage/mg"
	cli "github.com/threeport/threeport/pkg/cli/v0"
	tptdev "github.com/threeport/threeport/pkg/threeport-installer/v0/tptdev"
	util "github.com/threeport/threeport/pkg/util/v0"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
)

const releaseArch = "amd64"

// Build provides a type for methods that implement build targets.
type Build mg.Namespace

// Test provides a type for methods that implement test targets.
type Test mg.Namespace

// Install provides a type for methods that implement install targets.
type Install mg.Namespace

// Dev provides a type for methods that implement dev targets.
type Dev mg.Namespace

// Package provides a type for methods that implement package targets.
type Package mg.Namespace

// ApiBin builds the REST API binary.
func (Build) ApiBin(arch string) error {
	workingDir, _, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	if err := util.BuildBinaries(
		workingDir,
		[]string{arch},
		[]string{"cmd/rest-api"},
		false,
	); err != nil {
		return fmt.Errorf("failed to build rest-api binary: %w", err)
	}

	fmt.Printf("binary built and available at bin/%s/rest-api\n", arch)

	return nil
}

// ApiBinDev builds the REST API binary for the architcture of the machine
// where it is built.
func (Build) ApiBinDev() error {
	_, arch, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get local CPU architecture: %w", err)
	}

	build := Build{}
	if err := build.ApiBin(arch); err != nil {
		return fmt.Errorf("failed to build dev rest-api binary: %w", err)
	}

	return nil
}

// ApiBinRelease builds the REST API binary for release architecture.
func (Build) ApiBinRelease() error {
	build := Build{}
	if err := build.ApiBin(releaseArch); err != nil {
		return fmt.Errorf("failed to build release rest-api binary: %w", err)
	}

	return nil
}

// restApiImagePackage packages a pre-built REST API binary into a container image.
func (Build) restApiImagePackage(
	workingDir string,
	imageRepo string,
	imageTag string,
	arch string,
) error {
	if err := util.BuildImage(
		workingDir,
		"Dockerfile",
		"release",
		arch,
		"rest-api",
		"bin",
		nil,
		imageRepo,
		"threeport-django-rest-api",
		imageTag,
		true,
		false,
		"",
	); err != nil {
		return fmt.Errorf("failed to build and push rest-api image: %w", err)
	}

	return nil
}

// ApiImage builds and pushes a REST API container image.
func (Build) ApiImage(
	imageRepo string,
	imageTag string,
	arch string,
) error {
	workingDir, _, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	arches := util.ParseArches(arch)
	if err := util.BuildBinaries(
		workingDir,
		arches,
		[]string{"cmd/rest-api"},
		false,
	); err != nil {
		return fmt.Errorf("failed to build rest-api binary: %w", err)
	}

	return Build{}.restApiImagePackage(workingDir, imageRepo, imageTag, arch)
}

// ApiImageDev builds and pushes a development REST API container image.
func (Build) ApiImageDev() error {
	_, arch, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get local CPU architecture: %w", err)
	}

	build := Build{}
	if err := build.ApiImage(
		installer.DevImageNamespace,
		version.GetVersion(),
		arch,
	); err != nil {
		return fmt.Errorf("failed to build and push dev rest-api image: %w", err)
	}

	return nil
}

// ApiImageRelease builds and pushes a release REST API container image.
func (Build) ApiImageRelease() error {
	build := Build{}
	if err := build.ApiImage(
		installer.ReleaseImageNamespace,
		version.GetVersion(),
		releaseArch,
	); err != nil {
		return fmt.Errorf("failed to build and push release rest-api image: %w", err)
	}

	return nil
}

// DbMigratorBin builds the database migrator binary.
func (Build) DbMigratorBin(arch string) error {
	workingDir, _, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	if err := util.BuildBinaries(
		workingDir,
		[]string{arch},
		[]string{"cmd/database-migrator"},
		false,
	); err != nil {
		return fmt.Errorf("failed to build database-migrator binary: %w", err)
	}

	fmt.Printf("binary built and available at bin/%s/database-migrator\n", arch)

	return nil
}

// DbMigratorBinDev builds the database migrator binary for the architcture of the machine
// where it is built.
func (Build) DbMigratorBinDev() error {
	_, arch, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get local CPU architecture: %w", err)
	}

	build := Build{}
	if err := build.DbMigratorBin(arch); err != nil {
		return fmt.Errorf("failed to build dev database-migrator binary: %w", err)
	}

	return nil
}

// DbMigratorBinRelease builds the database migrator binary for release architecture.
func (Build) DbMigratorBinRelease() error {
	build := Build{}
	if err := build.DbMigratorBin(releaseArch); err != nil {
		return fmt.Errorf("failed to build release database-migrator binary: %w", err)
	}

	return nil
}

// dbMigratorImagePackage packages a pre-built database migrator binary into a container image.
func (Build) dbMigratorImagePackage(
	workingDir string,
	imageRepo string,
	imageTag string,
	arch string,
) error {
	if err := util.BuildImage(
		workingDir,
		"Dockerfile",
		"release",
		arch,
		"database-migrator",
		"bin",
		nil,
		imageRepo,
		"threeport-django-database-migrator",
		imageTag,
		true,
		false,
		"",
	); err != nil {
		return fmt.Errorf("failed to build and push database-migrator image: %w", err)
	}

	return nil
}

// DbMigratorImage builds and pushes a database migrator container image.
func (Build) DbMigratorImage(
	imageRepo string,
	imageTag string,
	arch string,
) error {
	workingDir, _, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	arches := util.ParseArches(arch)
	if err := util.BuildBinaries(
		workingDir,
		arches,
		[]string{"cmd/database-migrator"},
		false,
	); err != nil {
		return fmt.Errorf("failed to build database-migrator binary: %w", err)
	}

	return Build{}.dbMigratorImagePackage(workingDir, imageRepo, imageTag, arch)
}

// DbMigratorImageDev builds and pushes a development database migrator container image.
func (Build) DbMigratorImageDev() error {
	_, arch, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get local CPU architecture: %w", err)
	}

	build := Build{}
	if err := build.DbMigratorImage(
		installer.DevImageNamespace,
		version.GetVersion(),
		arch,
	); err != nil {
		return fmt.Errorf("failed to build and push dev database-migrator image: %w", err)
	}

	return nil
}

// DbMigratorImageRelease builds and pushes a release database migrator container image.
func (Build) DbMigratorImageRelease() error {
	build := Build{}
	if err := build.DbMigratorImage(
		installer.ReleaseImageNamespace,
		version.GetVersion(),
		releaseArch,
	); err != nil {
		return fmt.Errorf("failed to build and push release database-migrator image: %w", err)
	}

	return nil
}

// DjangoControllerBin builds the django-controller binary.
func (Build) DjangoControllerBin(arch string) error {
	workingDir, _, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	if err := util.BuildBinaries(
		workingDir,
		[]string{arch},
		[]string{"cmd/django-controller"},
		false,
	); err != nil {
		return fmt.Errorf("failed to build django-controller binary: %w", err)
	}

	fmt.Printf("binary built and available at bin/%s/django-controller\n", arch)

	return nil
}

// DjangoControllerBinDev builds the django-controller binary for the architcture of the machine
// where it is built.
func (Build) DjangoControllerBinDev() error {
	_, arch, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get local CPU architecture: %w", err)
	}

	build := Build{}
	if err := build.DjangoControllerBin(arch); err != nil {
		return fmt.Errorf("failed to build dev django-controller binary: %w", err)
	}

	return nil
}

// DjangoControllerBinRelease builds the django-controller binary for release architecture.
func (Build) DjangoControllerBinRelease() error {
	build := Build{}
	if err := build.DjangoControllerBin(releaseArch); err != nil {
		return fmt.Errorf("failed to build release django-controller binary: %w", err)
	}

	return nil
}

// djangoControllerImagePackage packages a pre-built django-controller binary into a container image.
func (Build) djangoControllerImagePackage(
	workingDir string,
	imageRepo string,
	imageTag string,
	arch string,
) error {
	if err := util.BuildImage(
		workingDir,
		"Dockerfile",
		"release",
		arch,
		"django-controller",
		"bin",
		nil,
		imageRepo,
		"threeport-django-django-controller",
		imageTag,
		true,
		false,
		"",
	); err != nil {
		return fmt.Errorf("failed to build and push django-controller image: %w", err)
	}

	return nil
}

// DjangoControllerImage builds and pushes a django-controller container image.
func (Build) DjangoControllerImage(
	imageRepo string,
	imageTag string,
	arch string,
) error {
	workingDir, _, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	arches := util.ParseArches(arch)
	if err := util.BuildBinaries(
		workingDir,
		arches,
		[]string{"cmd/django-controller"},
		false,
	); err != nil {
		return fmt.Errorf("failed to build django-controller binary: %w", err)
	}

	return Build{}.djangoControllerImagePackage(workingDir, imageRepo, imageTag, arch)
}

// DjangoControllerImageDev builds and pushes a development django-controller container image.
func (Build) DjangoControllerImageDev() error {
	_, arch, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get local CPU architecture: %w", err)
	}

	build := Build{}
	if err := build.DjangoControllerImage(
		installer.DevImageNamespace,
		version.GetVersion(),
		arch,
	); err != nil {
		return fmt.Errorf("failed to build and push dev django-controller image: %w", err)
	}

	return nil
}

// DjangoControllerImageRelease builds and pushes a release django-controller container image.
func (Build) DjangoControllerImageRelease() error {
	build := Build{}
	if err := build.DjangoControllerImage(
		installer.ReleaseImageNamespace,
		version.GetVersion(),
		releaseArch,
	); err != nil {
		return fmt.Errorf("failed to build and push release django-controller image: %w", err)
	}

	return nil
}

// AllBins builds the binaries for all components.
func (Build) AllBins(arch string) error {
	build := Build{}
	if err := build.ApiBin(arch); err != nil {
		return fmt.Errorf("failed to build binary: %w", err)
	}

	if err := build.DbMigratorBin(arch); err != nil {
		return fmt.Errorf("failed to build binary: %w", err)
	}

	if err := build.DjangoControllerBin(arch); err != nil {
		return fmt.Errorf("failed to build binary: %w", err)
	}

	return nil
}

// AllBinsDev builds the development binaries for all components.
func (Build) AllBinsDev() error {
	build := Build{}
	if err := build.ApiBinDev(); err != nil {
		return fmt.Errorf("failed to build binary: %w", err)
	}

	if err := build.DbMigratorBinDev(); err != nil {
		return fmt.Errorf("failed to build binary: %w", err)
	}

	if err := build.DjangoControllerBinDev(); err != nil {
		return fmt.Errorf("failed to build binary: %w", err)
	}

	return nil
}

// AllBinsRelease builds the release binaries for all components.
func (Build) AllBinsRelease() error {
	build := Build{}
	if err := build.ApiBinRelease(); err != nil {
		return fmt.Errorf("failed to build binary: %w", err)
	}

	if err := build.DbMigratorBinRelease(); err != nil {
		return fmt.Errorf("failed to build binary: %w", err)
	}

	if err := build.DjangoControllerBinRelease(); err != nil {
		return fmt.Errorf("failed to build binary: %w", err)
	}

	return nil
}

// AllImages builds and pushes images for all components. Pre-compiles
// binaries for every requested arch in parallel, then packages each
// component image in parallel. A multi-arch arch value (e.g. amd64,arm64)
// produces a multi-arch manifest in one push. A single arch (e.g. amd64)
// pushes only that arch under the given tag; use package:allManifests to
// stitch single-arch tags from separate runs into a multi-arch manifest list.
// Set PARALLEL_IMAGE_BUILD >= 1 to cap packaging concurrency (e.g.
// `PARALLEL_IMAGE_BUILD=4 mage build:allImages ghcr.io/foo v1 amd64,arm64`).
func (Build) AllImages(
	imageRepo string,
	imageTag string,
	arch string,
) error {
	// pre-compile every binary for every requested arch in one go build
	// per arch (arches run in parallel) so dependency compilation is
	// shared across components within an arch. Each per-image task
	// below then only packages the pre-built binary.
	workingDir, _, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	arches := util.ParseArches(arch)

	packageDirs := []string{
		"cmd/rest-api",
		"cmd/database-migrator",
		"cmd/django-controller",
	}

	if err := util.BuildBinaries(
		workingDir,
		arches,
		packageDirs,
		false,
	); err != nil {
		return fmt.Errorf("failed to pre-build binaries: %w", err)
	}

	build := Build{}
	wrap := func(fn func(string, string, string, string) error) func() error {
		return func() error {
			return fn(workingDir, imageRepo, imageTag, arch)
		}
	}
	tasks := []func() error{
		wrap(build.restApiImagePackage),
		wrap(build.dbMigratorImagePackage),
		wrap(build.djangoControllerImagePackage),
	}
	return util.RunParallel(parallelFromEnv(), tasks)
}

// AllImagesDev builds and pushes development images for all components.
// Set PARALLEL_IMAGE_BUILD >= 1 to control worker concurrency (e.g. `PARALLEL_IMAGE_BUILD=4 mage build:allImagesDev`).
func (Build) AllImagesDev() error {
	_, arch, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get local CPU architecture: %w", err)
	}

	// pre-compile every binary for every requested arch in one go build
	// per arch (arches run in parallel) so dependency compilation is
	// shared across components within an arch. Each per-image task
	// below then only packages the pre-built binary.
	workingDir, _, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	arches := util.ParseArches(arch)

	packageDirs := []string{
		"cmd/rest-api",
		"cmd/database-migrator",
		"cmd/django-controller",
	}

	if err := util.BuildBinaries(
		workingDir,
		arches,
		packageDirs,
		false,
	); err != nil {
		return fmt.Errorf("failed to pre-build binaries: %w", err)
	}

	build := Build{}
	wrap := func(fn func(string, string, string, string) error) func() error {
		return func() error {
			return fn(workingDir, installer.DevImageNamespace, version.GetVersion(), arch)
		}
	}
	tasks := []func() error{
		wrap(build.restApiImagePackage),
		wrap(build.dbMigratorImagePackage),
		wrap(build.djangoControllerImagePackage),
	}
	return util.RunParallel(parallelFromEnv(), tasks)
}

// Manifest stitches per-arch images into a multi-arch manifest list
// under the canonical tag. Sources are looked up at
// <repo>/<image>:<tag>-<arch> for each arch in the comma-separated
// arches list and combined into <repo>/<image>:<tag> via
// `docker buildx imagetools create`.
func (Package) Manifest(
	imageRepo string,
	imageName string,
	imageTag string,
	arches string,
) error {
	return util.PushMultiArchManifest(imageRepo, imageName, imageTag, arches)
}

// AllManifests stitches multi-arch manifest lists for every component
// in parallel, sourced from the installer's authoritative controller
// list so adding a new controller automatically extends coverage. Set
// PARALLEL_IMAGE_BUILD >= 1 to control worker concurrency (e.g.
// `PARALLEL_IMAGE_BUILD=4 mage package:allManifests ghcr.io/foo v1 amd64,arm64`).
func (Package) AllManifests(
	imageRepo string,
	imageTag string,
	arches string,
) error {
	// gather every component image emitted by the generator
	images := []string{
		"threeport-django-rest-api",
		"threeport-django-database-migrator",
		"threeport-django-django-controller",
	}

	tasks := make([]func() error, 0, len(images))
	for _, image := range images {
		image := image
		tasks = append(tasks, func() error {
			return util.PushMultiArchManifest(imageRepo, image, imageTag, arches)
		})
	}

	return util.RunParallel(parallelFromEnv(), tasks)
}

// parallelFromEnv returns the PARALLEL_IMAGE_BUILD env var as an int, defaulting to 1.
func parallelFromEnv() int {
	v := os.Getenv("PARALLEL_IMAGE_BUILD")
	if v == "" {
		return 1
	}
	n, err := strconv.Atoi(v)
	if err != nil || n < 1 {
		return 1
	}
	return n
}

// LoadImage builds and loads an image to the provided kind cluster.
func (Dev) LoadImage(kindClusterName string, component string) error {
	workingDir, arch, err := getBuildVals()
	if err != nil {
		return fmt.Errorf("failed to get build values: %w", err)
	}

	if err := util.BuildBinaries(
		workingDir,
		[]string{arch},
		[]string{fmt.Sprintf("cmd/%s", component)},
		false,
	); err != nil {
		return fmt.Errorf("failed to build binary: %w", err)
	}

	imageName := fmt.Sprintf("threeport-%s-%s", "django", component)

	dockerfileTarget := "release"

	if err := util.BuildImage(
		workingDir,
		"Dockerfile",
		dockerfileTarget,
		arch,
		component,
		"bin",
		nil,
		installer.DevImageNamespace,
		imageName,
		version.GetVersion(),
		false,
		true,
		kindClusterName,
	); err != nil {
		return fmt.Errorf("failed to build and load image: %w", err)
	}

	return nil
}

// Plugin compiles the extension's tptctl plugin.
func (Build) Plugin() error {
	buildCmd := exec.Command(
		"go",
		"build",
		"-o",
		"bin/django",
		"cmd/django/main_gen.go",
	)

	output, err := buildCmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("build failed for tptctl plugin with output '%s': %w", output, err)
	}

	fmt.Println("tptctl plugin built and available at bin/django")

	return nil
}

// Plugin builds the tptctl plugin and installs it in the tptctl plugin directory.
func (Install) Plugin() error {
	build := Build{}
	if err := build.Plugin(); err != nil {
		return fmt.Errorf("failed to build tptctl plugin: %w", err)
	}

	pluginDir := os.Getenv("THREEPORT_PLUGIN_DIR")
	if pluginDir == "" {
		dir, err := cli.DefaultPluginDir()
		if err != nil {
			return fmt.Errorf("failed to determine tptctl plugin directory: %w", err)
		}
		pluginDir = dir
	}
	if err := os.MkdirAll(pluginDir, 0o755); err != nil {
		return fmt.Errorf("failed to create tptctl plugin directory: %w", err)
	}

	outputPath := filepath.Join(pluginDir, "django")
	installCmd := exec.Command(
		"cp",
		"bin/django",
		outputPath,
	)

	output, err := installCmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("install failed for tptctl plugin with output '%s': %w", output, err)
	}

	fmt.Printf("tptctl plugin installed and available at %s\n", outputPath)

	return nil
}

// GenerateSwaggerDocs generates the API server swagger documentation served by the API.
func (Dev) GenerateSwaggerDocs() error {
	docsDestination := "pkg/api-server/v0/docs"
	swagCmd := exec.Command(
		"swag",
		"init",
		"--dir",
		"cmd/rest-api,pkg/api,pkg/api-server/v0",
		"--parseDependency",
		"--generalInfo",
		"main_gen.go",
		"--output",
		docsDestination,
	)

	output, err := swagCmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("API docs generation failed with output '%s': %w", output, err)
	}

	fmt.Printf("API docs generated in %s\n", docsDestination)

	return nil
}

// LocalRegistryUp starts a docker container to serve as a local container registry.
func (Dev) LocalRegistryUp() error {
	if err := tptdev.CreateLocalRegistry(); err != nil {
		return fmt.Errorf("failed to create local container registry: %w", err)
	}

	return nil
}

// LocalRegistryDown stops and removes the local container registry.
func (Dev) LocalRegistryDown() error {
	if err := tptdev.DeleteLocalRegistry(); err != nil {
		return fmt.Errorf("failed to remove local container registry: %w", err)
	}

	return nil
}

// getBuildVals returns the working directory and arch for builds.
func getBuildVals() (string, string, error) {
	workingDir, err := os.Getwd()
	if err != nil {
		return "", "", fmt.Errorf("failed to get working directory: %w", err)
	}

	arch := runtime.GOARCH

	return workingDir, arch, nil
}
