// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	"bytes"
	"context"
	"crypto/rsa"
	"crypto/x509"
	api_v0 "django-threeport-module/pkg/api/v0"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	tp_auth "github.com/threeport/threeport/pkg/auth/v0"
	v0 "github.com/threeport/threeport/pkg/cli/v0"
	client_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	kube "github.com/threeport/threeport/pkg/kube/v0"
	tp_installer "github.com/threeport/threeport/pkg/threeport-installer/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	errors "k8s.io/apimachinery/pkg/api/errors"
	meta "k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	dynamic "k8s.io/client-go/dynamic"
	"net/http"
	"os"
)

const (
	ReleaseImageNamespace     = "docker.io/juanqleet"
	DevImageNamespace         = "localhost:5001"
	DbInitFilename            = "db.sql"
	DbInitLocation            = "/etc/threeport/db-create"
	ThreeportApiConfigSecret  = "api-config"
	ModuleApiConfigSecret     = "module-api-config"
	defaultNamespace          = "threeport-django"
	defaultThreeportNamespace = "threeport-control-plane"
	apiServerName             = "threeport-django-api-server"
	tpApiCaSecretName         = "threeport-api-ca"
	tpApiCertSecretName       = "threeport-api-client-cert"
)

// Installer contains the values needed for a module installation.
type Installer struct {
	// dynamice interface client for Kubernetes API
	KubeClient dynamic.Interface

	// Kubernetes API REST mapper
	KubeRestMapper *meta.RESTMapper

	// The Kubernetes namespace to install the module components in.
	ModuleNamespace string

	// The Kubernetes namespace the Threeport control plane is installed in.
	ThreeportNamespace string

	// HTTP client for calls to the Threeport API. The module API server is
	// reached through the Threeport API, so this client is used to confirm the
	// module API server is serving before the install returns.
	ApiClient *http.Client

	// The Threeport API endpoint. Module routes are served through this
	// endpoint, so a module route is polled here to confirm readiness.
	ApiEndpoint string

	// The container image repository to pull module's API server and
	// controller/s' container images from.
	ControlPlaneImageRepo string

	// The container image tag to use for module's API server and
	// controller/s' container image.
	ControlPlaneImageTag string

	// If true, auth is enabled on Threeport API.
	AuthEnabled bool

	// If true, pod imagePullPolicy is set to Always so each rollout
	// re-pulls the tag. Use for development iteration where you push
	// a moving tag like 'dev-amd64' and want the cluster to pick up
	// the latest push without rotating tags.
	Debug bool

	// Path to a docker config JSON file. When set, the installer
	// creates a dockerconfigjson Secret from it and references that
	// Secret from each component's imagePullSecrets so the kubelet
	// can pull images from a private registry.
	ImagePullSecretFile string
}

// getImagePullPolicy returns Always when Debug is true so a moving
// dev tag is re-pulled on every pod restart, IfNotPresent otherwise.
func (i *Installer) getImagePullPolicy() string {
	if i.Debug {
		return "Always"
	}
	return "IfNotPresent"
}

// NewInstaller returns a django module installer with default values.
func NewInstaller(
	kubeClient dynamic.Interface,
	restMapper *meta.RESTMapper,
) *Installer {
	defaultInstaller := Installer{
		KubeClient:         kubeClient,
		KubeRestMapper:     restMapper,
		ModuleNamespace:    defaultNamespace,
		ThreeportNamespace: defaultThreeportNamespace,
	}

	return &defaultInstaller
}

// InstallDjangoModule installs the controller and API for the django module.
func (i *Installer) InstallDjangoModule() error {
	// create namespace
	var namespace = &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "Namespace",
			"metadata": map[string]interface{}{
				"name": i.ModuleNamespace,
			},
		},
	}

	if _, err := kube.CreateOrUpdateResource(
		namespace,
		i.KubeClient,
		*i.KubeRestMapper,
	); err != nil {
		return fmt.Errorf("failed to create/update django module namespace: %w", err)
	}

	// copy secrets into module namespace
	if err := copySecret(
		i.KubeClient,
		*i.KubeRestMapper,
		"db-root-cert",
		i.ThreeportNamespace,
		i.ModuleNamespace,
	); err != nil {
		return fmt.Errorf("failed to copy secret: %w", err)
	}

	if err := copySecret(
		i.KubeClient,
		*i.KubeRestMapper,
		"db-threeport-cert",
		i.ThreeportNamespace,
		i.ModuleNamespace,
	); err != nil {
		return fmt.Errorf("failed to copy secret: %w", err)
	}

	if err := copySecret(
		i.KubeClient,
		*i.KubeRestMapper,
		"encryption-key",
		i.ThreeportNamespace,
		i.ModuleNamespace,
	); err != nil {
		return fmt.Errorf("failed to copy secret: %w", err)
	}

	if err := copySecret(
		i.KubeClient,
		*i.KubeRestMapper,
		"controller-config",
		i.ThreeportNamespace,
		i.ModuleNamespace,
	); err != nil {
		return fmt.Errorf("failed to copy secret: %w", err)
	}

	if err := copySecret(
		i.KubeClient,
		*i.KubeRestMapper,
		"api-config",
		i.ThreeportNamespace,
		i.ModuleNamespace,
	); err != nil {
		return fmt.Errorf("failed to copy secret: %w", err)
	}

	// add secret for module API config
	var moduleApiSecret = &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "Secret",
			"metadata": map[string]interface{}{
				"name":      ModuleApiConfigSecret,
				"namespace": i.ModuleNamespace,
			},
			"stringData": map[string]interface{}{
				"env": fmt.Sprintf("MODULE_API_ENDPOINT=%[1]s.%[2]s.svc.cluster.local\nMODULE_NAMESPACE=%[2]s\nTHREEPORT_AUTH_ENABLED=%[3]t\n",
					apiServerName,
					i.ModuleNamespace,
					i.AuthEnabled,
				),
			},
		},
	}
	if _, err := kube.CreateOrUpdateResource(moduleApiSecret, i.KubeClient, *i.KubeRestMapper); err != nil {
		return fmt.Errorf("failed to create/update module API config secret: %w", err)
	}

	// optional image pull secret: when a docker config file is given,
	// create a dockerconfigjson Secret from it and reference it from
	// each component below so the kubelet can pull private images
	var imagePullSecrets = []interface{}{}
	if i.ImagePullSecretFile != "" {
		dockerConfig, err := os.ReadFile(i.ImagePullSecretFile)
		if err != nil {
			return fmt.Errorf("failed to read image pull secret file: %w", err)
		}
		var imagePullSecret = &unstructured.Unstructured{
			Object: map[string]interface{}{
				"apiVersion": "v1",
				"kind":       "Secret",
				"metadata": map[string]interface{}{
					"name":      "threeport-django-image-pull-secret",
					"namespace": i.ModuleNamespace,
				},
				"stringData": map[string]interface{}{
					".dockerconfigjson": string(dockerConfig),
				},
				"type": "kubernetes.io/dockerconfigjson",
			},
		}
		if _, err := kube.CreateOrUpdateResource(imagePullSecret, i.KubeClient, *i.KubeRestMapper); err != nil {
			return fmt.Errorf("failed to create/update image pull secret: %w", err)
		}
		imagePullSecrets = []interface{}{
			map[string]interface{}{
				"name": "threeport-django-image-pull-secret",
			},
		}
	}

	// create configmap used to initialize API database
	var dbCreateConfig = &unstructured.Unstructured{Object: map[string]interface{}{
		"apiVersion": "v1",
		"data": map[string]interface{}{
			"db.sql": "CREATE USER IF NOT EXISTS threeport;\nCREATE DATABASE IF NOT EXISTS threeport_django_api encoding='utf-8';\nGRANT ALL ON DATABASE threeport_django_api TO threeport;",
		},
		"kind": "ConfigMap",
		"metadata": map[string]interface{}{
			"name":      "db-create",
			"namespace": i.ModuleNamespace,
		},
	}}

	if _, err := kube.CreateOrUpdateResource(dbCreateConfig, i.KubeClient, *i.KubeRestMapper); err != nil {
		return fmt.Errorf("failed to create/update django DB initialization configmap: %w", err)
	}

	// establish volumes and volume mounts for the Threeport API server creds as needed
	tpAuthVolumes := []interface{}{}
	tpAuthVolumeMounts := []interface{}{}
	if i.AuthEnabled {
		// if auth is enabled, get the Threeport API server CA cert and key from
		// the Kubernetes cluster.
		caCert, caKey, err := i.getApiCa()
		if err != nil {
			return fmt.Errorf("failed to retrieve Threeport API CA cert and key: %w", err)
		}

		// load the cert and key
		x509CaCert, rsaCaKey, err := loadApiCa(caCert, caKey)
		if err != nil {
			return fmt.Errorf("failed to load Threeport API CA cert and key: %w", err)
		}

		// build the module API server service fqdn so the cert covers the name
		// the core uses when it proxies requests to this module over https
		moduleApiServiceName := fmt.Sprintf("%s.%s.svc.cluster.local", apiServerName, i.ModuleNamespace)

		// generate a cert and key for the controller that connects to the
		// Threeport API and for the module API server that serves https; the cert
		// subject carries the control plane organizational unit and the alt name
		// covers the module API server service fqdn
		clientCert, clientKey, err := tp_auth.GenerateCertificate(x509CaCert, rsaCaKey, "django-threeport-module", "threeport.io", tp_auth.OUControlPlane, moduleApiServiceName)
		if err != nil {
			return fmt.Errorf("failed to generate client cert and key for django controller: %w", err)
		}

		// create secrets for controller to load credentials from
		if err := i.createAuthCertSecrets(string(caCert), clientCert, clientKey); err != nil {
			return fmt.Errorf("failed to create client auth certs for django controller: %w", err)
		}

		// add the volumes and volume mounts for deployment manifest
		tpAuthVolumes = getTpAuthVolumes()
		tpAuthVolumeMounts = getTpAuthVolumeMounts()
	}

	// install django API server deployment
	apiArgs := []interface{}{"-auto-migrate=true"}
	if !i.AuthEnabled {
		apiArgs = append(apiArgs, "-auth-enabled=false")
	}
	apiVolumes := tpAuthVolumes
	apiVolumes = append(apiVolumes, map[string]interface{}{
		"name": "db-root-cert",
		"secret": map[string]interface{}{
			"defaultMode": 420,
			"secretName":  "db-root-cert",
		},
	})
	apiVolumes = append(apiVolumes, map[string]interface{}{
		"name": "db-threeport-cert",
		"secret": map[string]interface{}{
			"defaultMode": 420,
			"secretName":  "db-threeport-cert",
		},
	})
	apiVolumes = append(apiVolumes, map[string]interface{}{
		"name": ThreeportApiConfigSecret,
		"secret": map[string]interface{}{
			"defaultMode": 420,
			"secretName":  ThreeportApiConfigSecret,
		},
	})
	apiVolumes = append(apiVolumes, map[string]interface{}{
		"name": ModuleApiConfigSecret,
		"secret": map[string]interface{}{
			"defaultMode": 420,
			"secretName":  ModuleApiConfigSecret,
		},
	})
	apiVolumes = append(apiVolumes, map[string]interface{}{
		"configMap": map[string]interface{}{
			"defaultMode": 420,
			"name":        "db-create",
		},
		"name": "db-create",
	})
	apiVolumeMounts := tpAuthVolumeMounts
	apiVolumeMounts = append(apiVolumeMounts, map[string]interface{}{
		"mountPath": "/etc/threeport/",
		"name":      ThreeportApiConfigSecret,
	})
	apiVolumeMounts = append(apiVolumeMounts, map[string]interface{}{
		"mountPath": "/etc/threeport/mod/",
		"name":      ModuleApiConfigSecret,
	})
	apiVolumeMounts = append(apiVolumeMounts, map[string]interface{}{
		"mountPath": "/etc/threeport/db-certs",
		"name":      "db-threeport-cert",
	})
	var djangoApiDeploy = &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "apps/v1",
			"kind":       "Deployment",
			"metadata": map[string]interface{}{
				"name":      apiServerName,
				"namespace": i.ModuleNamespace,
			},
			"spec": map[string]interface{}{
				"replicas": 1,
				"selector": map[string]interface{}{
					"matchLabels": map[string]interface{}{
						"app.kubernetes.io/name": apiServerName,
					},
				},
				"strategy": map[string]interface{}{
					"rollingUpdate": map[string]interface{}{
						"maxSurge":       "25%",
						"maxUnavailable": "25%",
					},
					"type": "RollingUpdate",
				},
				"template": map[string]interface{}{
					"metadata": map[string]interface{}{
						"creationTimestamp": nil,
						"labels": map[string]interface{}{
							"app.kubernetes.io/name": apiServerName,
						},
					},
					"spec": map[string]interface{}{
						"containers": []interface{}{
							map[string]interface{}{
								"args": apiArgs,
								"command": []interface{}{
									"/rest-api",
								},
								"envFrom": []interface{}{
									map[string]interface{}{
										"secretRef": map[string]interface{}{
											"name": "encryption-key",
										},
									},
								},
								"image": fmt.Sprintf(
									"%s/threeport-django-rest-api:%s",
									i.ControlPlaneImageRepo,
									i.ControlPlaneImageTag,
								),
								"imagePullPolicy": i.getImagePullPolicy(),
								"name":            "api-server",
								"ports": []interface{}{
									map[string]interface{}{
										"containerPort": 1323,
										"name":          "api",
										"protocol":      "TCP",
									},
								},
								"readinessProbe": map[string]interface{}{
									"failureThreshold": 1,
									"httpGet": map[string]interface{}{
										"path":   "/readyz",
										"port":   8081,
										"scheme": "HTTP",
									},
									"initialDelaySeconds": 1,
									"periodSeconds":       2,
									"successThreshold":    1,
									"timeoutSeconds":      1,
								},
								"volumeMounts": apiVolumeMounts,
							},
						},
						"imagePullSecrets": imagePullSecrets,
						"initContainers": []interface{}{
							map[string]interface{}{
								"command": []interface{}{
									"bash",
									"-c",
									fmt.Sprintf("cockroach sql --certs-dir=/etc/threeport/db-certs --host crdb.%s.svc.cluster.local --port 26257 -f /etc/threeport/db-create/db.sql", i.ThreeportNamespace),
								},
								"image":           "docker.io/cockroachdb/cockroach:v23.1.14",
								"imagePullPolicy": i.getImagePullPolicy(),
								"name":            "db-init",
								"volumeMounts": []interface{}{
									map[string]interface{}{
										"mountPath": "/etc/threeport/db-create",
										"name":      "db-create",
									},
									map[string]interface{}{
										"mountPath": "/etc/threeport/db-certs",
										"name":      "db-root-cert",
									},
								},
							},
							map[string]interface{}{
								"args": []interface{}{
									"-env-file=/etc/threeport/env",
									"up",
								},
								"command": []interface{}{
									"/database-migrator",
								},
								"image": fmt.Sprintf(
									"%s/threeport-django-database-migrator:%s",
									i.ControlPlaneImageRepo,
									i.ControlPlaneImageTag,
								),
								"imagePullPolicy": i.getImagePullPolicy(),
								"name":            "database-migrator",
								"volumeMounts": []interface{}{
									map[string]interface{}{
										"mountPath": "/etc/threeport/",
										"name":      ThreeportApiConfigSecret,
									},
									map[string]interface{}{
										"mountPath": "/etc/threeport/db-certs",
										"name":      "db-threeport-cert",
									},
								},
							},
						},
						"restartPolicy":                 "Always",
						"terminationGracePeriodSeconds": 30,
						"volumes":                       apiVolumes,
					},
				},
			},
		},
	}

	if _, err := kube.CreateOrUpdateResource(djangoApiDeploy, i.KubeClient, *i.KubeRestMapper); err != nil {
		return fmt.Errorf("failed to create/update django API deployment: %w", err)
	}

	// install django API server service
	// serve mtls over https when auth is enabled, plain http otherwise
	apiServicePortName := "http"
	apiServicePort := 80
	if i.AuthEnabled {
		apiServicePortName = "https"
		apiServicePort = 443
	}
	var djangoApiService = &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "Service",
			"metadata": map[string]interface{}{
				"labels": map[string]interface{}{
					"app.kubernetes.io/name": apiServerName,
				},
				"name":      apiServerName,
				"namespace": i.ModuleNamespace,
			},
			"spec": map[string]interface{}{
				"ports": []interface{}{
					map[string]interface{}{
						"name":       apiServicePortName,
						"port":       apiServicePort,
						"protocol":   "TCP",
						"targetPort": 1323,
					},
				},
				"selector": map[string]interface{}{
					"app.kubernetes.io/name": apiServerName,
				},
			},
		},
	}
	if _, err := kube.CreateOrUpdateResource(djangoApiService, i.KubeClient, *i.KubeRestMapper); err != nil {
		return fmt.Errorf("failed to create/updated django API service: %w", err)
	}

	// install django controller/s
	// set auth enabled flag if auth not enabled (default is true)
	controllerArgs := []interface{}{}
	if !i.AuthEnabled {
		controllerArgs = append(controllerArgs, "-auth-enabled=false")
	}

	var DjangoControllerDeploy = &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "apps/v1",
			"kind":       "Deployment",
			"metadata": map[string]interface{}{
				"name":      "threeport-django-django-controller",
				"namespace": i.ModuleNamespace,
			},
			"spec": map[string]interface{}{
				"replicas": 1,
				"selector": map[string]interface{}{
					"matchLabels": map[string]interface{}{
						"app.kubernetes.io/name": "threeport-django-django-controller",
					},
				},
				"strategy": map[string]interface{}{
					"rollingUpdate": map[string]interface{}{
						"maxSurge":       "25%",
						"maxUnavailable": "25%",
					},
					"type": "RollingUpdate",
				},
				"template": map[string]interface{}{
					"metadata": map[string]interface{}{
						"labels": map[string]interface{}{
							"app.kubernetes.io/name": "threeport-django-django-controller",
						},
					},
					"spec": map[string]interface{}{
						"containers": []interface{}{
							map[string]interface{}{
								"args": controllerArgs,
								"command": []interface{}{
									"/django-controller",
								},
								"envFrom": []interface{}{
									map[string]interface{}{
										"secretRef": map[string]interface{}{
											"name": "controller-config",
										},
									},
									map[string]interface{}{
										"secretRef": map[string]interface{}{
											"name": "encryption-key",
										},
									},
								},
								"image": fmt.Sprintf(
									"%s/threeport-django-django-controller:%s",
									i.ControlPlaneImageRepo,
									i.ControlPlaneImageTag,
								),
								"imagePullPolicy": i.getImagePullPolicy(),
								"name":            "django-django-controller",
								"readinessProbe": map[string]interface{}{
									"failureThreshold": 1,
									"httpGet": map[string]interface{}{
										"path":   "/readyz",
										"port":   8081,
										"scheme": "HTTP",
									},
									"initialDelaySeconds": 1,
									"periodSeconds":       2,
									"successThreshold":    1,
									"timeoutSeconds":      1,
								},
								"volumeMounts": tpAuthVolumeMounts,
							},
						},
						"imagePullSecrets":              imagePullSecrets,
						"restartPolicy":                 "Always",
						"terminationGracePeriodSeconds": 30,
						"volumes":                       tpAuthVolumes,
					},
				},
			},
		},
	}

	if _, err := kube.CreateOrUpdateResource(DjangoControllerDeploy, i.KubeClient, *i.KubeRestMapper); err != nil {
		return fmt.Errorf("failed to create/update django controller deployment: %w", err)
	}

	// wait for the module API server to start serving
	v0.Info(fmt.Sprintf("Waiting for django module API to start running at %s", i.ApiEndpoint))
	attemptsMax := 60
	waitDurationSeconds := 5
	if err := util.Retry(
		attemptsMax,
		waitDurationSeconds,
		func() error {
			_, err := client_lib.GetResponse(
				i.ApiClient,
				fmt.Sprintf("%s%s", i.ApiEndpoint, api_v0.PathDjangoDefinitions),
				http.MethodGet,
				bytes.NewBuffer([]byte{}),
				map[string]string{},
				http.StatusOK,
			)
			if err != nil {
				v0.Info(fmt.Sprintf("Connection attempt result: %s", err))
				return fmt.Errorf("failed to reach django module API: %w", err)
			}
			return nil
		},
	); err != nil {
		return fmt.Errorf("timed out after %d seconds waiting for 200 response from django module API: %w", attemptsMax*waitDurationSeconds, err)
	}
	v0.Info("Django module API is running")

	return nil
}

// copySecret copies a secret from one namespace to another.  The function
// returns without error if the secret already exists in the target namespace.
func copySecret(
	dynamicClient dynamic.Interface,
	restMapper meta.RESTMapper,
	secretName string,
	sourceNamespace string,
	targetNamespace string,
) error {
	secretGVR := schema.GroupVersionResource{
		Group:    "",
		Resource: "secrets",
		Version:  "v1",
	}
	secretGK := schema.GroupKind{
		Group: "",
		Kind:  "Secret",
	}

	mapping, err := restMapper.RESTMapping(secretGK, secretGVR.Version)
	if err != nil {
		return fmt.Errorf("failed to get RESTMapping for Secret resource: %w", err)
	}

	targetSecretResource := dynamicClient.Resource(mapping.Resource).Namespace(targetNamespace)
	_, err = targetSecretResource.Get(context.TODO(), secretName, metav1.GetOptions{})
	if err == nil {
		// secret already exists, return nil
		return nil
	} else if !errors.IsNotFound(err) {
		return fmt.Errorf(
			"failed to check if Secret '%s' exists in namespace '%s': %w",
			secretName,
			targetNamespace,
			err,
		)
	}

	secretResource := dynamicClient.Resource(mapping.Resource).Namespace(sourceNamespace)
	secret, err := secretResource.Get(context.TODO(), secretName, metav1.GetOptions{})
	if err != nil {
		return fmt.Errorf(
			"failed to get Secret '%s' from namespace '%s': %w",
			secretName,
			sourceNamespace,
			err,
		)
	}

	secret.SetNamespace(targetNamespace)
	secret.SetResourceVersion("")
	secret.SetUID("")
	secret.SetSelfLink("")
	secret.SetCreationTimestamp(metav1.Time{})
	secret.SetManagedFields(nil)

	_, err = targetSecretResource.Create(context.TODO(), secret, metav1.CreateOptions{})
	if err != nil {
		return fmt.Errorf("failed to create/update Secret in namespace '%s': %w", targetNamespace, err)
	}

	return nil
}

// getApiCa gets the Threeport API CA cert secret from the Kubernetes cluster
// and returns the base 64 decoded string value for the CA cert and key.
func (i *Installer) getApiCa() ([]byte, []byte, error) {
	// get secret resource
	apiCaSecret, err := kube.GetResource(
		"core",
		"v1",
		"Secret",
		i.ThreeportNamespace,
		tp_installer.ThreeportApiCaSecret,
		i.KubeClient,
		*i.KubeRestMapper,
	)
	if err != nil {
		return []byte{}, []byte{}, fmt.Errorf("failed to get Threeport API CA secret from Kubernetes cluster: %w", err)
	}

	// retrieve 'data' field
	data, found, err := unstructured.NestedMap(apiCaSecret.Object, "data")
	if err != nil {
		return []byte{}, []byte{}, fmt.Errorf("failed to retrieve 'data' field: %w", err)
	}
	if !found {
		return []byte{}, []byte{}, fmt.Errorf("'data' field not found in the secret")
	}

	// extract and decode tls.crt
	tlsCrtBase64, found := data["tls.crt"].(string)
	if !found {
		return []byte{}, []byte{}, fmt.Errorf("'tls.crt' not found in the secret data")
	}
	tlsCrtBytes, err := base64.StdEncoding.DecodeString(tlsCrtBase64)
	if err != nil {
		return []byte{}, []byte{}, fmt.Errorf("failed to decode 'tls.crt': %w", err)
	}

	// extract and decode tls.key
	tlsKeyBase64, found := data["tls.key"].(string)
	if !found {
		return []byte{}, []byte{}, fmt.Errorf("'tls.key' not found in the secret data")
	}
	tlsKeyBytes, err := base64.StdEncoding.DecodeString(tlsKeyBase64)
	if err != nil {
		return []byte{}, []byte{}, fmt.Errorf("failed to decode 'tls.key': %w", err)
	}

	return tlsCrtBytes, tlsKeyBytes, nil
}

// loadApiCa takes the PEM encoded CA cert and key as strings and returns the
// x509.Certificate and rsa.PrivateKey objects.
func loadApiCa(caCertPem, caKeyPem []byte) (*x509.Certificate, *rsa.PrivateKey, error) {
	// decode PEM to extract the certificate
	block, _ := pem.Decode(caCertPem)
	if block == nil || block.Type != "CERTIFICATE" {
		return nil, nil, fmt.Errorf("failed to decode CA certificate PEM")
	}

	// Parse the certificate
	caCert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to parse CA certificate: %w", err)
	}

	// decode PEM to extract the private key
	block, _ = pem.Decode(caKeyPem)
	if block == nil || block.Type != "RSA PRIVATE KEY" {
		return nil, nil, fmt.Errorf("failed to decode CA private key PEM")
	}

	// Parse the RSA private key
	caPrivateKey, err := x509.ParsePKCS1PrivateKey(block.Bytes)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to parse CA private key: %w", err)
	}

	return caCert, caPrivateKey, nil
}

// createAuthCertSecrets creates the Kubernetes secrets needed for a controller
// to connect to the Threeport API.
func (i *Installer) createAuthCertSecrets(caCert, clientCert, clientKey string) error {
	var caCertSecret = &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "Secret",
			"metadata": map[string]interface{}{
				"name":      tpApiCaSecretName,
				"namespace": i.ModuleNamespace,
			},
			"stringData": map[string]interface{}{
				"tls.crt": caCert,
			},
			"type": "Opaque",
		},
	}
	if _, err := kube.CreateOrUpdateResource(caCertSecret, i.KubeClient, *i.KubeRestMapper); err != nil {
		return fmt.Errorf("failed to create/update django CA cert secret: %w", err)
	}

	var clientCertSecret = &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "Secret",
			"metadata": map[string]interface{}{
				"name":      tpApiCertSecretName,
				"namespace": i.ModuleNamespace,
			},
			"stringData": map[string]interface{}{
				"tls.crt": clientCert,
				"tls.key": clientKey,
			},
			"type": "kubernetes.io/tls",
		},
	}
	if _, err := kube.CreateOrUpdateResource(clientCertSecret, i.KubeClient, *i.KubeRestMapper); err != nil {
		return fmt.Errorf("failed to create/update django client cert secret: %w", err)
	}

	return nil
}

// getTpAuthVolumes returns the volumes for the CA and client certs needed for a
// controller to authenticate to the Threeport API.
func getTpAuthVolumes() []interface{} {
	return []interface{}{
		map[string]interface{}{
			"name": tpApiCaSecretName,
			"secret": map[string]interface{}{
				"secretName": tpApiCaSecretName,
			},
		},
		map[string]interface{}{
			"name": tpApiCertSecretName,
			"secret": map[string]interface{}{
				"secretName": tpApiCertSecretName,
			},
		},
	}
}

// getTpAuthVolumeMounts returns the volume mounts for the CA and client certs needed
// for a controller to authenticate to the Threeport API.
func getTpAuthVolumeMounts() []interface{} {
	return []interface{}{
		map[string]interface{}{
			"mountPath": "/etc/threeport/ca",
			"name":      tpApiCaSecretName,
		},
		map[string]interface{}{
			"mountPath": "/etc/threeport/cert",
			"name":      tpApiCertSecretName,
		},
	}
}
