// boilerplate generated by 'threeport-sdk gen' - do not edit

package handlers

import (
	nats "github.com/nats-io/nats.go"
	tp_handlers "github.com/threeport/threeport/pkg/api-server/v0/handlers"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// Handler is a wrapper for the threeport Handler object.
type Handler struct {
	Handler tp_handlers.Handler
}

// New returns a new Handler.
func New(db *gorm.DB, nc *nats.Conn, rc nats.JetStreamContext, logger *zap.Logger) Handler {
	handler := tp_handlers.New(db, nc, rc, logger)
	return Handler{Handler: handler}
}
