// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// DjangoConfig is a container for a Django which is a config abstraction for
// the DjangoDefinition and DjangoInstance API objects.
// This abstraction allows users to manage definitions and instances together with single operations
// rather than separate operations for each API object.
type DjangoConfig struct {
	Django DjangoValues
}

// DjangoValues contains all the attributes needed to manage the
// DjangoDefinition and DjangoInstance API objects
// together with a single operation.
type DjangoValues struct {
	// TODO: add fields needed for user to manage a DjangoDefinition and DjangoInstance together
	Name *string
	Age  *string
}

// Get gets a django definition and instance from the Threeport API.
func (d *DjangoConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]DjangoConfig, error) {
	// get operations
	operations, djangoDefinitions, djangoInstances := d.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute get operations
	if err := operations.Get(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute get operations for django defined instances: %w",
			err,
		)
	}

	// assemble the defined instances
	djangoConfigs := mapToDjangoDefinedInstances(djangoDefinitions, djangoInstances)

	return djangoConfigs, nil
}

// Create creates a django definition and instance in the Threeport API.
func (d *DjangoConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]DjangoConfig, error) {
	// get operations
	operations, djangoDefinitions, djangoInstances := d.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute create operations
	if err := operations.Create(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute create operations for django defined instance with name %s: %w",
			*d.Django.Name,
			err,
		)
	}

	// assemble the defined instances
	djangoConfigs := mapToDjangoDefinedInstances(djangoDefinitions, djangoInstances)

	return djangoConfigs, nil
}

// Replace replaces a django definition and instance in the Threeport API.
func (d *DjangoConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*[]DjangoConfig, error) {
	// get operations
	operations, djangoDefinitions, djangoInstances := d.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute replace operations
	if err := operations.Replace(name); err != nil {
		return nil, fmt.Errorf(
			"failed to execute replace operations for django defined instance with name %s: %w",
			name,
			err,
		)
	}

	// assemble the defined instances
	djangoConfigs := mapToDjangoDefinedInstances(djangoDefinitions, djangoInstances)

	return djangoConfigs, nil
}

// Delete deletes a django definition and instance from the Threeport API.
func (d *DjangoConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]DjangoConfig, error) {
	// get operations
	operations, _, _ := d.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute delete operations
	if err := operations.Delete(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute delete operations for django defined instance with name %s: %w",
			*d.Django.Name,
			err,
		)
	}

	return nil, nil
}

// GetOperations returns a slice of operations used to get, create, replace or delete
// a django defined instance.
func (d *DjangoConfig) GetOperations(
	apiClient *http.Client,
	apiEndpoint string,
) (*util.Operations, *[]DjangoDefinitionConfig, *[]DjangoInstanceConfig) {
	djangoValues := d.Django
	var err error
	var operatedDjangoDefinitions []DjangoDefinitionConfig
	var operatedDjangoInstances []DjangoInstanceConfig

	operations := util.Operations{}

	// add django definition operation
	// TODO: add appropriate fields to definition values object
	djangoDefinitionConfig := DjangoDefinitionConfig{
		DjangoDefinition: DjangoDefinitionValues{
			Age:  djangoValues.Age,
			Name: djangoValues.Name,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			djangoDefinition, err := djangoDefinitionConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create django definition with name %s: %w", *djangoValues.Name, err)
			}
			operatedDjangoDefinitions = append(operatedDjangoDefinitions, *djangoDefinition)
			return nil
		},
		Delete: func() error {
			_, err = djangoDefinitionConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete django definition with name %s: %w", *djangoValues.Name, err)
			}
			return nil
		},
		Get: func() error {
			djangoDefinitions, err := djangoDefinitionConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get django definitions: %w", err)
			}
			operatedDjangoDefinitions = append(operatedDjangoDefinitions, *djangoDefinitions...)
			return nil
		},
		Name: "django definition",
		Replace: func(name string) error {
			djangoDefinition, err := djangoDefinitionConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace django definition with name %s: %w", name, err)
			}
			operatedDjangoDefinitions = append(operatedDjangoDefinitions, *djangoDefinition)
			return nil
		},
	})

	// add django instance operation
	// TODO: add appropriate fields to instance values object
	djangoInstanceConfig := DjangoInstanceConfig{
		DjangoInstance: DjangoInstanceValues{
			Age:  djangoValues.Age,
			Name: djangoValues.Name,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			djangoInstance, err := djangoInstanceConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create django instance with name %s: %w", *djangoValues.Name, err)
			}
			operatedDjangoInstances = append(operatedDjangoInstances, *djangoInstance)
			return nil
		},
		Delete: func() error {
			_, err = djangoInstanceConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete django instance with name %s: %w", *djangoValues.Name, err)
			}
			return nil
		},
		Get: func() error {
			djangoInstances, err := djangoInstanceConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get django instances: %w", err)
			}
			operatedDjangoInstances = append(operatedDjangoInstances, *djangoInstances...)
			return nil
		},
		Name: "django instance",
		Replace: func(name string) error {
			djangoInstance, err := djangoInstanceConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace django instance with name %s: %w", name, err)
			}
			operatedDjangoInstances = append(operatedDjangoInstances, *djangoInstance)
			return nil
		},
	})

	return &operations, &operatedDjangoDefinitions, &operatedDjangoInstances
}

// mapToDjangoDefinedInstances maps a slice of django definition and instance configs
// to a slice of django config objects
func mapToDjangoDefinedInstances(
	djangoDefinitions *[]DjangoDefinitionConfig,
	djangoInstances *[]DjangoInstanceConfig,
) *[]DjangoConfig {
	var djangoConfigs []DjangoConfig
	for _, inst := range *djangoInstances {
		for _, def := range *djangoDefinitions {
			instName := *inst.DjangoInstance.Name
			defName := *def.DjangoDefinition.Name
			// a defined instance must have matching names for definition and instance
			// and the definition must be associated with the instance
			if instName == defName && *inst.DjangoInstance.DjangoDefinition.Name == *def.DjangoDefinition.Name {
				// TODO: add fields needed for user to manage a DjangoDefinition and DjangoInstance together
				djangoConfig := DjangoConfig{
					Django: DjangoValues{
						Age:  inst.DjangoInstance.Age,
						Name: inst.DjangoInstance.Name,
					},
				}
				djangoConfigs = append(djangoConfigs, djangoConfig)
				// an instance can only have one matching definition for a defined instance
				// we can break out of the loop after finding the first matching definition
				break
			}
		}
	}

	return &djangoConfigs
}
