// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	api_v0 "django-threeport-module/pkg/api/v0"
	client_v0 "django-threeport-module/pkg/client/v0"
	errors "errors"
	"fmt"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// DjangoInstanceConfig is a config abstraction for the DjangoInstance API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type DjangoInstanceConfig struct {
	DjangoInstance DjangoInstanceValues
}

// DjangoInstanceValues contains all the attributes needed to manage
// the DjangoInstance API object.
type DjangoInstanceValues struct {
	// TODO: add config abstraction fields needed for user to manage a DjangoInstance
	Name             *string
	DjangoDefinition *DjangoDefinitionValues
	Age              *string
}

// Get gets django instances from the Threeport API.
// If the name is set in the DjangoInstanceValues, it will return the django instance with that name.
// If the name is not set, it will return all django instances.
func (d *DjangoInstanceConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// get API objects
	var djangoInstances *[]api_v0.DjangoInstance
	switch {
	// if name is provided, get django instance by name
	case djangoInstanceValues.Name != nil:
		djangoInstance, err := client_v0.GetDjangoInstanceByName(apiClient, apiEndpoint, *djangoInstanceValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get django instance with name %s: %w", *djangoInstanceValues.Name, err)
		}
		djangoInstances = &[]api_v0.DjangoInstance{*djangoInstance}
	// get all django instances
	default:
		allDjangoInstances, err := client_v0.GetDjangoInstances(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get django instances from Threeport API: %w", err)
		}
		djangoInstances = allDjangoInstances
	}

	// assemble config objects from API objects
	var djangoInstanceConfigs []DjangoInstanceConfig
	for _, djangoInstance := range *djangoInstances {
		// TODO: add config abstraction fields needed for user to manage a DjangoInstance
		djangoInstanceConfig := DjangoInstanceConfig{
			DjangoInstance: DjangoInstanceValues{
				Age:  util.Ptr(util.GetAgeFormatted(djangoInstance.CreatedAt)),
				Name: djangoInstance.Name,
			},
		}
		djangoInstanceConfigs = append(djangoInstanceConfigs, djangoInstanceConfig)
	}

	return &djangoInstanceConfigs, nil
}

// Create creates a django instance in the Threeport API.
func (d *DjangoInstanceConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// validate config
	if err := d.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for django instance with name %s: %w", *djangoInstanceValues.Name, err)
	}

	// construct django instance object
	// TODO: add API object fields as needed for DjangoInstance
	djangoInstance := api_v0.DjangoInstance{
		Instance: tpapi_v0.Instance{
			Name: djangoInstanceValues.Name,
		},
	}

	// create django instance
	createdDjangoInstance, err := client_v0.CreateDjangoInstance(
		apiClient,
		apiEndpoint,
		&djangoInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create django instance in threeport API: %w", err)
	}

	// construct django instance config
	// TODO: add config abstraction fields needed for user to manage a DjangoInstance
	createdDjangoInstanceConfig := &DjangoInstanceConfig{
		DjangoInstance: DjangoInstanceValues{
			Age:  util.Ptr(util.GetAgeFormatted(createdDjangoInstance.CreatedAt)),
			Name: createdDjangoInstance.Name,
		},
	}

	return createdDjangoInstanceConfig, nil
}

// Replace updates the entire django instance object in the Threeport API.
// This is a full replacement of all fields in the django instance object.
// This function takes a name parameter to identify the django instance to replace.
// This allows a different name to be provided in the values object for name changes.
func (d *DjangoInstanceConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// validate config
	if err := d.Validate(); err != nil {
		return nil, fmt.Errorf("invalid django instance config: %w", err)
	}

	// get existing django instance by name
	existingDjangoInstance, err := client_v0.GetDjangoInstanceByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find django instance with name %s: %w", name, err)
	}

	// construct updated django instance object
	// TODO: add API object fields as needed for DjangoInstance
	updatedDjangoInstance := &api_v0.DjangoInstance{
		Common: tpapi_v0.Common{
			ID: existingDjangoInstance.ID,
		},
		Instance: tpapi_v0.Instance{
			Name: djangoInstanceValues.Name,
		},
	}

	// replace django instance
	replacedDjangoInstance, err := client_v0.ReplaceDjangoInstance(
		apiClient,
		apiEndpoint,
		updatedDjangoInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace django instance in threeport API: %w", err)
	}

	// construct updated django instance config
	// TODO: add config abstraction fields needed for user to manage a DjangoInstance
	updatedDjangoInstanceConfig := &DjangoInstanceConfig{
		DjangoInstance: DjangoInstanceValues{
			Age:  util.Ptr(util.GetAgeFormatted(replacedDjangoInstance.CreatedAt)),
			Name: replacedDjangoInstance.Name,
		},
	}

	return updatedDjangoInstanceConfig, nil
}

// Delete deletes a django instance from the Threeport API.
func (d *DjangoInstanceConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// get django instance by name
	djangoInstance, err := client_v0.GetDjangoInstanceByName(
		apiClient,
		apiEndpoint,
		*djangoInstanceValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find django instance with name %s: %w", *djangoInstanceValues.Name, err)
	}

	// delete django instance
	deletedDjangoInstance, err := client_v0.DeleteDjangoInstance(
		apiClient,
		apiEndpoint,
		*djangoInstance.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete django instance from Threeport API: %w", err)
	}

	// construct deleted django instance config
	// TODO: add config abstraction fields needed for user to manage a DjangoInstance
	deletedDjangoInstanceConfig := &DjangoInstanceConfig{
		DjangoInstance: DjangoInstanceValues{
			Name: deletedDjangoInstance.Name,
		},
	}

	return deletedDjangoInstanceConfig, nil
}

// Validate validates inputs to create django instances.
func (d *DjangoInstanceConfig) Validate() error {
	djangoInstanceValues := d.DjangoInstance
	multiError := util.MultiError{}

	// ensure name is set
	if djangoInstanceValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// TODO: add additional validation as needed

	return multiError.Error()
}
