// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	api_v0 "django-threeport-module/pkg/api/v0"
	client_v0 "django-threeport-module/pkg/client/v0"
	errors "errors"
	"fmt"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// DjangoDefinitionConfig is a config abstraction for the DjangoDefinition API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type DjangoDefinitionConfig struct {
	DjangoDefinition DjangoDefinitionValues
}

// DjangoDefinitionValues contains all the attributes needed to manage
// the DjangoDefinition API object.
type DjangoDefinitionValues struct {
	// TODO: add config abstraction fields needed for user to manage a DjangoDefinition
	Name *string
	Age  *string
}

// Get gets django definitions from the Threeport API.
// If the name is set in the DjangoDefinitionValues, it will return the django definition with that name.
// If the name is not set, it will return all django definitions.
func (d *DjangoDefinitionConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]DjangoDefinitionConfig, error) {
	djangoDefinitionValues := d.DjangoDefinition

	// get API objects
	var djangoDefinitions *[]api_v0.DjangoDefinition
	switch {
	// if name is provided, get django definition by name
	case djangoDefinitionValues.Name != nil:
		djangoDefinition, err := client_v0.GetDjangoDefinitionByName(apiClient, apiEndpoint, *djangoDefinitionValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get django definition with name %s: %w", *djangoDefinitionValues.Name, err)
		}
		djangoDefinitions = &[]api_v0.DjangoDefinition{*djangoDefinition}
	// get all django definitions
	default:
		allDjangoDefinitions, err := client_v0.GetDjangoDefinitions(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get django definitions from Threeport API: %w", err)
		}
		djangoDefinitions = allDjangoDefinitions
	}

	// assemble config objects from API objects
	var djangoDefinitionConfigs []DjangoDefinitionConfig
	for _, djangoDefinition := range *djangoDefinitions {
		// TODO: add config abstraction fields needed for user to manage a DjangoDefinition
		djangoDefinitionConfig := DjangoDefinitionConfig{
			DjangoDefinition: DjangoDefinitionValues{
				Age:  util.Ptr(util.GetAgeFormatted(djangoDefinition.CreatedAt)),
				Name: djangoDefinition.Name,
			},
		}
		djangoDefinitionConfigs = append(djangoDefinitionConfigs, djangoDefinitionConfig)
	}

	return &djangoDefinitionConfigs, nil
}

// Create creates a django definition in the Threeport API.
func (d *DjangoDefinitionConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*DjangoDefinitionConfig, error) {
	djangoDefinitionValues := d.DjangoDefinition

	// validate config
	if err := d.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for django definition with name %s: %w", *djangoDefinitionValues.Name, err)
	}

	// construct django definition object
	// TODO: add API object fields as needed for DjangoDefinition
	djangoDefinition := api_v0.DjangoDefinition{
		Definition: tpapi_v0.Definition{
			Name: djangoDefinitionValues.Name,
		},
	}

	// create django definition
	createdDjangoDefinition, err := client_v0.CreateDjangoDefinition(
		apiClient,
		apiEndpoint,
		&djangoDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create django definition in threeport API: %w", err)
	}

	// construct django definition config
	// TODO: add config abstraction fields needed for user to manage a DjangoDefinition
	createdDjangoDefinitionConfig := &DjangoDefinitionConfig{
		DjangoDefinition: DjangoDefinitionValues{
			Age:  util.Ptr(util.GetAgeFormatted(createdDjangoDefinition.CreatedAt)),
			Name: createdDjangoDefinition.Name,
		},
	}

	return createdDjangoDefinitionConfig, nil
}

// Replace updates the entire django definition object in the Threeport API.
// This is a full replacement of all fields in the django definition object.
// This function takes a name parameter to identify the django definition to replace.
// This allows a different name to be provided in the values object for name changes.
func (d *DjangoDefinitionConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*DjangoDefinitionConfig, error) {
	djangoDefinitionValues := d.DjangoDefinition

	// validate config
	if err := d.Validate(); err != nil {
		return nil, fmt.Errorf("invalid django definition config: %w", err)
	}

	// get existing django definition by name
	existingDjangoDefinition, err := client_v0.GetDjangoDefinitionByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find django definition with name %s: %w", name, err)
	}

	// construct updated django definition object
	// TODO: add API object fields as needed for DjangoDefinition
	updatedDjangoDefinition := &api_v0.DjangoDefinition{
		Common: tpapi_v0.Common{
			ID: existingDjangoDefinition.ID,
		},
		Definition: tpapi_v0.Definition{
			Name: djangoDefinitionValues.Name,
		},
	}

	// replace django definition
	replacedDjangoDefinition, err := client_v0.ReplaceDjangoDefinition(
		apiClient,
		apiEndpoint,
		updatedDjangoDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace django definition in threeport API: %w", err)
	}

	// construct updated django definition config
	// TODO: add config abstraction fields needed for user to manage a DjangoDefinition
	updatedDjangoDefinitionConfig := &DjangoDefinitionConfig{
		DjangoDefinition: DjangoDefinitionValues{
			Age:  util.Ptr(util.GetAgeFormatted(replacedDjangoDefinition.CreatedAt)),
			Name: replacedDjangoDefinition.Name,
		},
	}

	return updatedDjangoDefinitionConfig, nil
}

// Delete deletes a django definition from the Threeport API.
func (d *DjangoDefinitionConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*DjangoDefinitionConfig, error) {
	djangoDefinitionValues := d.DjangoDefinition

	// get django definition by name
	djangoDefinition, err := client_v0.GetDjangoDefinitionByName(
		apiClient,
		apiEndpoint,
		*djangoDefinitionValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find django definition with name %s: %w", *djangoDefinitionValues.Name, err)
	}

	// delete django definition
	deletedDjangoDefinition, err := client_v0.DeleteDjangoDefinition(
		apiClient,
		apiEndpoint,
		*djangoDefinition.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete django definition from Threeport API: %w", err)
	}

	// construct deleted django definition config
	// TODO: add config abstraction fields needed for user to manage a DjangoDefinition
	deletedDjangoDefinitionConfig := &DjangoDefinitionConfig{
		DjangoDefinition: DjangoDefinitionValues{
			Name: deletedDjangoDefinition.Name,
		},
	}

	return deletedDjangoDefinitionConfig, nil
}

// Validate validates inputs to create django definitions.
func (d *DjangoDefinitionConfig) Validate() error {
	djangoDefinitionValues := d.DjangoDefinition
	multiError := util.MultiError{}

	// ensure name is set
	if djangoDefinitionValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// TODO: add additional validation as needed

	return multiError.Error()
}
