// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	api_v0 "django-threeport-module/pkg/api/v0"
	client_v0 "django-threeport-module/pkg/client/v0"
	errors "errors"
	"fmt"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	tpclient_v0 "github.com/threeport/threeport/pkg/client/v0"
	tpconfig_v0 "github.com/threeport/threeport/pkg/config/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// DjangoInstanceConfig is a config abstraction for the DjangoInstance API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type DjangoInstanceConfig struct {
	DjangoInstance DjangoInstanceValues
}

// DjangoInstanceValues contains all the attributes needed to manage
// the DjangoInstance API object.
type DjangoInstanceValues struct {
	Name *string

	// The Kubernetes runtime to deploy to, named rather than referenced by ID.
	// Left unset, the control plane's default runtime is used, so a user with
	// one cluster does not have to name it.
	KubernetesRuntimeInstance *tpconfig_v0.KubernetesRuntimeInstanceValues

	// When a DomainName is in use, the subdomain to reach this instance on.
	SubDomain *string

	DjangoDefinition *DjangoDefinitionValues

	Age *string
}

// Get gets django instances from the Threeport API.
// If the name is set in the DjangoInstanceValues, it will return the django instance with that name.
// If the name is not set, it will return all django instances.
func (d *DjangoInstanceConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// get API objects
	var djangoInstances *[]api_v0.DjangoInstance
	switch {
	// if name is provided, get django instance by name
	case djangoInstanceValues.Name != nil:
		djangoInstance, err := client_v0.GetDjangoInstanceByName(apiClient, apiEndpoint, *djangoInstanceValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get django instance with name %s: %w", *djangoInstanceValues.Name, err)
		}
		djangoInstances = &[]api_v0.DjangoInstance{*djangoInstance}
	// get all django instances
	default:
		allDjangoInstances, err := client_v0.GetDjangoInstances(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get django instances from Threeport API: %w", err)
		}
		djangoInstances = allDjangoInstances
	}

	// assemble config objects from API objects
	var djangoInstanceConfigs []DjangoInstanceConfig
	for _, djangoInstance := range *djangoInstances {
		// the runtime and definition are foreign keys on the API object; the
		// config abstraction exists so the user sees names instead
		var kubernetesRuntimeInstanceValues *tpconfig_v0.KubernetesRuntimeInstanceValues
		if djangoInstance.KubernetesRuntimeInstanceID != nil {
			kubernetesRuntimeInstance, err := tpclient_v0.GetKubernetesRuntimeInstanceByID(
				apiClient,
				apiEndpoint,
				*djangoInstance.KubernetesRuntimeInstanceID,
			)
			if err != nil {
				return nil, fmt.Errorf(
					"failed to get kubernetes runtime instance with ID %d: %w",
					*djangoInstance.KubernetesRuntimeInstanceID, err,
				)
			}
			kubernetesRuntimeInstanceValues = &tpconfig_v0.KubernetesRuntimeInstanceValues{
				Name: kubernetesRuntimeInstance.Name,
			}
		}

		var djangoDefinitionValues *DjangoDefinitionValues
		if djangoInstance.DjangoDefinitionID != nil {
			djangoDefinition, err := client_v0.GetDjangoDefinitionByID(
				apiClient,
				apiEndpoint,
				*djangoInstance.DjangoDefinitionID,
			)
			if err != nil {
				return nil, fmt.Errorf(
					"failed to get django definition with ID %d: %w",
					*djangoInstance.DjangoDefinitionID, err,
				)
			}
			djangoDefinitionValues = &DjangoDefinitionValues{Name: djangoDefinition.Name}
		}

		djangoInstanceConfig := DjangoInstanceConfig{
			DjangoInstance: DjangoInstanceValues{
				Name:                      djangoInstance.Name,
				KubernetesRuntimeInstance: kubernetesRuntimeInstanceValues,
				SubDomain:                 djangoInstance.SubDomain,
				DjangoDefinition:          djangoDefinitionValues,
				Age:                       util.Ptr(util.GetAgeFormatted(djangoInstance.CreatedAt)),
			},
		}
		djangoInstanceConfigs = append(djangoInstanceConfigs, djangoInstanceConfig)
	}

	return &djangoInstanceConfigs, nil
}

// Create creates a django instance in the Threeport API.
func (d *DjangoInstanceConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// validate config
	if err := d.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for django instance with name %s: %w", *djangoInstanceValues.Name, err)
	}

	// resolve the runtime and definition the config names into the foreign keys
	// the API object carries
	kubernetesRuntimeInstance, err := getKubernetesRuntimeInstanceByNameOrDefault(
		apiClient,
		apiEndpoint,
		djangoInstanceValues.KubernetesRuntimeInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}

	djangoDefinition, err := client_v0.GetDjangoDefinitionByName(
		apiClient,
		apiEndpoint,
		*djangoInstanceValues.DjangoDefinition.Name,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to find django definition with name %s: %w",
			*djangoInstanceValues.DjangoDefinition.Name, err,
		)
	}

	// construct django instance object
	djangoInstance := api_v0.DjangoInstance{
		Instance: tpapi_v0.Instance{
			Name: djangoInstanceValues.Name,
		},
		KubernetesRuntimeInstanceID: kubernetesRuntimeInstance.ID,
		SubDomain:                   djangoInstanceValues.SubDomain,
		DjangoDefinitionID:          djangoDefinition.ID,
	}

	// create django instance
	createdDjangoInstance, err := client_v0.CreateDjangoInstance(
		apiClient,
		apiEndpoint,
		&djangoInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create django instance in threeport API: %w", err)
	}

	// construct django instance config
	createdDjangoInstanceConfig := &DjangoInstanceConfig{
		DjangoInstance: DjangoInstanceValues{
			Name: createdDjangoInstance.Name,
			KubernetesRuntimeInstance: &tpconfig_v0.KubernetesRuntimeInstanceValues{
				Name: kubernetesRuntimeInstance.Name,
			},
			SubDomain:        createdDjangoInstance.SubDomain,
			DjangoDefinition: &DjangoDefinitionValues{Name: djangoDefinition.Name},
			Age:              util.Ptr(util.GetAgeFormatted(createdDjangoInstance.CreatedAt)),
		},
	}

	return createdDjangoInstanceConfig, nil
}

// Replace updates the entire django instance object in the Threeport API.
// This is a full replacement of all fields in the django instance object.
// This function takes a name parameter to identify the django instance to replace.
// This allows a different name to be provided in the values object for name changes.
func (d *DjangoInstanceConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// validate config
	if err := d.Validate(); err != nil {
		return nil, fmt.Errorf("invalid django instance config: %w", err)
	}

	// get existing django instance by name
	existingDjangoInstance, err := client_v0.GetDjangoInstanceByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find django instance with name %s: %w", name, err)
	}

	// resolve the names the config carries into foreign keys
	kubernetesRuntimeInstance, err := getKubernetesRuntimeInstanceByNameOrDefault(
		apiClient,
		apiEndpoint,
		djangoInstanceValues.KubernetesRuntimeInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}

	djangoDefinition, err := client_v0.GetDjangoDefinitionByName(
		apiClient,
		apiEndpoint,
		*djangoInstanceValues.DjangoDefinition.Name,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to find django definition with name %s: %w",
			*djangoInstanceValues.DjangoDefinition.Name, err,
		)
	}

	// construct updated django instance object. This is a full replacement, so
	// every field the user can set is sent rather than merged onto the existing
	// object.
	updatedDjangoInstance := &api_v0.DjangoInstance{
		Common: tpapi_v0.Common{
			ID: existingDjangoInstance.ID,
		},
		Instance: tpapi_v0.Instance{
			Name: djangoInstanceValues.Name,
		},
		KubernetesRuntimeInstanceID: kubernetesRuntimeInstance.ID,
		SubDomain:                   djangoInstanceValues.SubDomain,
		DjangoDefinitionID:          djangoDefinition.ID,
	}

	// replace django instance
	replacedDjangoInstance, err := client_v0.ReplaceDjangoInstance(
		apiClient,
		apiEndpoint,
		updatedDjangoInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace django instance in threeport API: %w", err)
	}

	// construct updated django instance config
	updatedDjangoInstanceConfig := &DjangoInstanceConfig{
		DjangoInstance: DjangoInstanceValues{
			Name: replacedDjangoInstance.Name,
			KubernetesRuntimeInstance: &tpconfig_v0.KubernetesRuntimeInstanceValues{
				Name: kubernetesRuntimeInstance.Name,
			},
			SubDomain:        replacedDjangoInstance.SubDomain,
			DjangoDefinition: &DjangoDefinitionValues{Name: djangoDefinition.Name},
			Age:              util.Ptr(util.GetAgeFormatted(replacedDjangoInstance.CreatedAt)),
		},
	}

	return updatedDjangoInstanceConfig, nil
}

// Delete deletes a django instance from the Threeport API.
func (d *DjangoInstanceConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*DjangoInstanceConfig, error) {
	djangoInstanceValues := d.DjangoInstance

	// get django instance by name
	djangoInstance, err := client_v0.GetDjangoInstanceByName(
		apiClient,
		apiEndpoint,
		*djangoInstanceValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find django instance with name %s: %w", *djangoInstanceValues.Name, err)
	}

	// delete django instance
	deletedDjangoInstance, err := client_v0.DeleteDjangoInstance(
		apiClient,
		apiEndpoint,
		*djangoInstance.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete django instance from Threeport API: %w", err)
	}

	// wait for the django instance to be deleted. The API marks it for deletion
	// and the reconciler tears the workload down before the row goes away, so
	// returning immediately would let a caller deleting a defined instance try
	// to remove the definition while this instance still refers to it - which
	// the API refuses. Threeport's own instance configs wait the same way.
	util.Retry(60, 1, func() error {
		if _, err := client_v0.GetDjangoInstanceByName(apiClient, apiEndpoint, *djangoInstanceValues.Name); err == nil {
			return errors.New("django instance not deleted")
		}

		return nil
	})

	// construct deleted django instance config
	deletedDjangoInstanceConfig := &DjangoInstanceConfig{
		DjangoInstance: DjangoInstanceValues{
			Name: deletedDjangoInstance.Name,
		},
	}

	return deletedDjangoInstanceConfig, nil
}

// Validate validates inputs to create django instances.
func (d *DjangoInstanceConfig) Validate() error {
	djangoInstanceValues := d.DjangoInstance
	multiError := util.MultiError{}

	// ensure name is set
	if djangoInstanceValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// an instance has nothing to deploy without a definition, and Create
	// dereferences the name to look it up
	if djangoInstanceValues.DjangoDefinition == nil || djangoInstanceValues.DjangoDefinition.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: DjangoDefinition.Name"))
	}

	return multiError.Error()
}
